"""Generated protobuf code for CVT gRPC service."""

from .cvt_pb2 import (
    RegisterSchemaRequest,
    RegisterSchemaResponse,
    GetSchemaRequest,
    GetSchemaResponse,
    SchemaMetadata,
    SchemaOwnership as ProtoSchemaOwnership,
    InteractionRequest,
    ValidationResult,
    RequestData,
    ResponseData,
    CompareSchemasRequest,
    CompareSchemasResponse,
    BreakingChange as ProtoBreakingChange,
    GenerateFixtureRequest,
    GenerateFixtureResponse,
    GeneratedFixture as ProtoGeneratedFixture,
    GeneratedRequest as ProtoGeneratedRequest,
    GeneratedResponse as ProtoGeneratedResponse,
    ListEndpointsRequest,
    ListEndpointsResponse,
    EndpointInfo as ProtoEndpointInfo,
    OutputType,
    ValidateProducerRequest,
    # Consumer Registry
    RegisterConsumerRequest,
    RegisterConsumerResponse,
    ListConsumersRequest,
    ListConsumersResponse,
    DeregisterConsumerRequest,
    DeregisterConsumerResponse,
    ConsumerInfo as ProtoConsumerInfo,
    EndpointUsage as ProtoEndpointUsage,
    # Deployment Safety
    CanIDeployRequest,
    CanIDeployResponse,
    ConsumerImpact as ProtoConsumerImpact,
)
from .cvt_pb2_grpc import ContractValidatorStub

__all__ = [
    "RegisterSchemaRequest",
    "RegisterSchemaResponse",
    "GetSchemaRequest",
    "GetSchemaResponse",
    "SchemaMetadata",
    "ProtoSchemaOwnership",
    "InteractionRequest",
    "ValidationResult",
    "RequestData",
    "ResponseData",
    "CompareSchemasRequest",
    "CompareSchemasResponse",
    "ProtoBreakingChange",
    "GenerateFixtureRequest",
    "GenerateFixtureResponse",
    "ProtoGeneratedFixture",
    "ProtoGeneratedRequest",
    "ProtoGeneratedResponse",
    "ListEndpointsRequest",
    "ListEndpointsResponse",
    "ProtoEndpointInfo",
    "OutputType",
    "ContractValidatorStub",
    "ValidateProducerRequest",
    # Consumer Registry
    "RegisterConsumerRequest",
    "RegisterConsumerResponse",
    "ListConsumersRequest",
    "ListConsumersResponse",
    "DeregisterConsumerRequest",
    "DeregisterConsumerResponse",
    "ProtoConsumerInfo",
    "ProtoEndpointUsage",
    # Deployment Safety
    "CanIDeployRequest",
    "CanIDeployResponse",
    "ProtoConsumerImpact",
]
