// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: api/protos/cvt.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BreakingChangeType int32

const (
	BreakingChangeType_BREAKING_CHANGE_UNSPECIFIED BreakingChangeType = 0
	BreakingChangeType_ENDPOINT_REMOVED            BreakingChangeType = 1 // Endpoint path+method was removed
	BreakingChangeType_REQUIRED_FIELD_ADDED        BreakingChangeType = 2 // Required field added to request body
	BreakingChangeType_TYPE_CHANGED                BreakingChangeType = 3 // Field type changed incompatibly
	BreakingChangeType_REQUIRED_PARAMETER_ADDED    BreakingChangeType = 4 // Required query/path/header param added
	BreakingChangeType_RESPONSE_SCHEMA_CHANGED     BreakingChangeType = 5 // Response schema changed incompatibly
	BreakingChangeType_ENUM_VALUE_REMOVED          BreakingChangeType = 6 // Enum value was removed
)

// Enum value maps for BreakingChangeType.
var (
	BreakingChangeType_name = map[int32]string{
		0: "BREAKING_CHANGE_UNSPECIFIED",
		1: "ENDPOINT_REMOVED",
		2: "REQUIRED_FIELD_ADDED",
		3: "TYPE_CHANGED",
		4: "REQUIRED_PARAMETER_ADDED",
		5: "RESPONSE_SCHEMA_CHANGED",
		6: "ENUM_VALUE_REMOVED",
	}
	BreakingChangeType_value = map[string]int32{
		"BREAKING_CHANGE_UNSPECIFIED": 0,
		"ENDPOINT_REMOVED":            1,
		"REQUIRED_FIELD_ADDED":        2,
		"TYPE_CHANGED":                3,
		"REQUIRED_PARAMETER_ADDED":    4,
		"RESPONSE_SCHEMA_CHANGED":     5,
		"ENUM_VALUE_REMOVED":          6,
	}
)

func (x BreakingChangeType) Enum() *BreakingChangeType {
	p := new(BreakingChangeType)
	*p = x
	return p
}

func (x BreakingChangeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BreakingChangeType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_protos_cvt_proto_enumTypes[0].Descriptor()
}

func (BreakingChangeType) Type() protoreflect.EnumType {
	return &file_api_protos_cvt_proto_enumTypes[0]
}

func (x BreakingChangeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BreakingChangeType.Descriptor instead.
func (BreakingChangeType) EnumDescriptor() ([]byte, []int) {
	return file_api_protos_cvt_proto_rawDescGZIP(), []int{0}
}

type OutputType int32

const (
	OutputType_OUTPUT_FIXTURE  OutputType = 0 // Complete request/response pair (default)
	OutputType_OUTPUT_REQUEST  OutputType = 1 // Request body only
	OutputType_OUTPUT_RESPONSE OutputType = 2 // Response only
)

// Enum value maps for OutputType.
var (
	OutputType_name = map[int32]string{
		0: "OUTPUT_FIXTURE",
		1: "OUTPUT_REQUEST",
		2: "OUTPUT_RESPONSE",
	}
	OutputType_value = map[string]int32{
		"OUTPUT_FIXTURE":  0,
		"OUTPUT_REQUEST":  1,
		"OUTPUT_RESPONSE": 2,
	}
)

func (x OutputType) Enum() *OutputType {
	p := new(OutputType)
	*p = x
	return p
}

func (x OutputType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OutputType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_protos_cvt_proto_enumTypes[1].Descriptor()
}

func (OutputType) Type() protoreflect.EnumType {
	return &file_api_protos_cvt_proto_enumTypes[1]
}

func (x OutputType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OutputType.Descriptor instead.
func (OutputType) EnumDescriptor() ([]byte, []int) {
	return file_api_protos_cvt_proto_rawDescGZIP(), []int{1}
}

// Schema ownership and governance information
type SchemaOwnership struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`                                   // Owner name or identifier
	Team          string                 `protobuf:"bytes,2,opt,name=team,proto3" json:"team,omitempty"`                                     // Team responsible for the schema
	ContactEmail  string                 `protobuf:"bytes,3,opt,name=contact_email,json=contactEmail,proto3" json:"contact_email,omitempty"` // Contact email for schema issues
	ReadOnly      bool                   `protobuf:"varint,4,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`            // If true, schema cannot be updated
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchemaOwnership) Reset() {
	*x = SchemaOwnership{}
	mi := &file_api_protos_cvt_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchemaOwnership) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemaOwnership) ProtoMessage() {}

func (x *SchemaOwnership) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_cvt_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemaOwnership.ProtoReflect.Descriptor instead.
func (*SchemaOwnership) Descriptor() ([]byte, []int) {
	return file_api_protos_cvt_proto_rawDescGZIP(), []int{0}
}

func (x *SchemaOwnership) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *SchemaOwnership) GetTeam() string {
	if x != nil {
		return x.Team
	}
	return ""
}

func (x *SchemaOwnership) GetContactEmail() string {
	if x != nil {
		return x.ContactEmail
	}
	return ""
}

func (x *SchemaOwnership) GetReadOnly() bool {
	if x != nil {
		return x.ReadOnly
	}
	return false
}

// Metadata about a registered schema
type SchemaMetadata struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SchemaId       string                 `protobuf:"bytes,1,opt,name=schema_id,json=schemaId,proto3" json:"schema_id,omitempty"`                // Unique identifier
	SchemaVersion  string                 `protobuf:"bytes,2,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"` // Semantic version (e.g., "1.2.3")
	SchemaHash     string                 `protobuf:"bytes,3,opt,name=schema_hash,json=schemaHash,proto3" json:"schema_hash,omitempty"`          // SHA256 hash of schema content
	RegisteredAt   int64                  `protobuf:"varint,4,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`   // Unix timestamp of initial registration
	UpdatedAt      int64                  `protobuf:"varint,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`            // Unix timestamp of last update
	Ownership      *SchemaOwnership       `protobuf:"bytes,6,opt,name=ownership,proto3" json:"ownership,omitempty"`
	OpenapiVersion string                 `protobuf:"bytes,7,opt,name=openapi_version,json=openapiVersion,proto3" json:"openapi_version,omitempty"` // Detected OpenAPI version (e.g., "3.0.0")
	EndpointCount  int32                  `protobuf:"varint,8,opt,name=endpoint_count,json=endpointCount,proto3" json:"endpoint_count,omitempty"`   // Number of endpoints in schema
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SchemaMetadata) Reset() {
	*x = SchemaMetadata{}
	mi := &file_api_protos_cvt_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchemaMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemaMetadata) ProtoMessage() {}

func (x *SchemaMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_cvt_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemaMetadata.ProtoReflect.Descriptor instead.
func (*SchemaMetadata) Descriptor() ([]byte, []int) {
	return file_api_protos_cvt_proto_rawDescGZIP(), []int{1}
}

func (x *SchemaMetadata) GetSchemaId() string {
	if x != nil {
		return x.SchemaId
	}
	return ""
}

func (x *SchemaMetadata) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *SchemaMetadata) GetSchemaHash() string {
	if x != nil {
		return x.SchemaHash
	}
	return ""
}

func (x *SchemaMetadata) GetRegisteredAt() int64 {
	if x != nil {
		return x.RegisteredAt
	}
	return 0
}

func (x *SchemaMetadata) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *SchemaMetadata) GetOwnership() *SchemaOwnership {
	if x != nil {
		return x.Ownership
	}
	return nil
}

func (x *SchemaMetadata) GetOpenapiVersion() string {
	if x != nil {
		return x.OpenapiVersion
	}
	return ""
}

func (x *SchemaMetadata) GetEndpointCount() int32 {
	if x != nil {
		return x.EndpointCount
	}
	return 0
}

type RegisterSchemaRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	SchemaId           string                 `protobuf:"bytes,1,opt,name=schema_id,json=schemaId,proto3" json:"schema_id,omitempty"`                                // Unique identifier for the schema
	SchemaContent      string                 `protobuf:"bytes,2,opt,name=schema_content,json=schemaContent,proto3" json:"schema_content,omitempty"`                 // The OpenAPI spec content (YAML or JSON)
	SchemaVersion      string                 `protobuf:"bytes,3,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`                 // Optional semantic version
	Ownership          *SchemaOwnership       `protobuf:"bytes,4,opt,name=ownership,proto3" json:"ownership,omitempty"`                                              // Optional ownership information
	CheckCompatibility bool                   `protobuf:"varint,5,opt,name=check_compatibility,json=checkCompatibility,proto3" json:"check_compatibility,omitempty"` // If true, check for breaking changes
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RegisterSchemaRequest) Reset() {
	*x = RegisterSchemaRequest{}
	mi := &file_api_protos_cvt_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterSchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterSchemaRequest) ProtoMessage() {}

func (x *RegisterSchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_cvt_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterSchemaRequest.ProtoReflect.Descriptor instead.
func (*RegisterSchemaRequest) Descriptor() ([]byte, []int) {
	return file_api_protos_cvt_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterSchemaRequest) GetSchemaId() string {
	if x != nil {
		return x.SchemaId
	}
	return ""
}

func (x *RegisterSchemaRequest) GetSchemaContent() string {
	if x != nil {
		return x.SchemaContent
	}
	return ""
}

func (x *RegisterSchemaRequest) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *RegisterSchemaRequest) GetOwnership() *SchemaOwnership {
	if x != nil {
		return x.Ownership
	}
	return nil
}

func (x *RegisterSchemaRequest) GetCheckCompatibility() bool {
	if x != nil {
		return x.CheckCompatibility
	}
	return false
}

type RegisterSchemaResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Success         bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message         string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Metadata        *SchemaMetadata        `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`                                      // Metadata for the registered schema
	BreakingChanges []*BreakingChange      `protobuf:"bytes,4,rep,name=breaking_changes,json=breakingChanges,proto3" json:"breaking_changes,omitempty"` // Breaking changes if any detected
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RegisterSchemaResponse) Reset() {
	*x = RegisterSchemaResponse{}
	mi := &file_api_protos_cvt_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterSchemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterSchemaResponse) ProtoMessage() {}

func (x *RegisterSchemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_cvt_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterSchemaResponse.ProtoReflect.Descriptor instead.
func (*RegisterSchemaResponse) Descriptor() ([]byte, []int) {
	return file_api_protos_cvt_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterSchemaResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterSchemaResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterSchemaResponse) GetMetadata() *SchemaMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *RegisterSchemaResponse) GetBreakingChanges() []*BreakingChange {
	if x != nil {
		return x.BreakingChanges
	}
	return nil
}

type InteractionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaId      string                 `protobuf:"bytes,1,opt,name=schema_id,json=schemaId,proto3" json:"schema_id,omitempty"`
	Request       *RequestData           `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	Response      *ResponseData          `protobuf:"bytes,3,opt,name=response,proto3" json:"response,omitempty"`
	SchemaVersion string                 `protobuf:"bytes,4,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"` // Optional: validate against specific version
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InteractionRequest) Reset() {
	*x = InteractionRequest{}
	mi := &file_api_protos_cvt_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InteractionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InteractionRequest) ProtoMessage() {}

func (x *InteractionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_cvt_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InteractionRequest.ProtoReflect.Descriptor instead.
func (*InteractionRequest) Descriptor() ([]byte, []int) {
	return file_api_protos_cvt_proto_rawDescGZIP(), []int{4}
}

func (x *InteractionRequest) GetSchemaId() string {
	if x != nil {
		return x.SchemaId
	}
	return ""
}

func (x *InteractionRequest) GetRequest() *RequestData {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *InteractionRequest) GetResponse() *ResponseData {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *InteractionRequest) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

type RequestData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"` // GET, POST, etc.
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`     // /users/123
	Headers       map[string]string      `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          string                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"` // JSON body as string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestData) Reset() {
	*x = RequestData{}
	mi := &file_api_protos_cvt_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestData) ProtoMessage() {}

func (x *RequestData) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_cvt_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestData.ProtoReflect.Descriptor instead.
func (*RequestData) Descriptor() ([]byte, []int) {
	return file_api_protos_cvt_proto_rawDescGZIP(), []int{5}
}

func (x *RequestData) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *RequestData) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *RequestData) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *RequestData) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type ResponseData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"` // JSON body as string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseData) Reset() {
	*x = ResponseData{}
	mi := &file_api_protos_cvt_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseData) ProtoMessage() {}

func (x *ResponseData) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_cvt_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseData.ProtoReflect.Descriptor instead.
func (*ResponseData) Descriptor() ([]byte, []int) {
	return file_api_protos_cvt_proto_rawDescGZIP(), []int{6}
}

func (x *ResponseData) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *ResponseData) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *ResponseData) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type ValidationResult struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Valid                   bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Errors                  []string               `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	ValidatedAgainstVersion string                 `protobuf:"bytes,3,opt,name=validated_against_version,json=validatedAgainstVersion,proto3" json:"validated_against_version,omitempty"` // Version of schema used for validation
	ValidatedAgainstHash    string                 `protobuf:"bytes,4,opt,name=validated_against_hash,json=validatedAgainstHash,proto3" json:"validated_against_hash,omitempty"`          // Hash of schema used for validation
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ValidationResult) Reset() {
	*x = ValidationResult{}
	mi := &file_api_protos_cvt_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationResult) ProtoMessage() {}

func (x *ValidationResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_cvt_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationResult.ProtoReflect.Descriptor instead.
func (*ValidationResult) Descriptor() ([]byte, []int) {
	return file_api_protos_cvt_proto_rawDescGZIP(), []int{7}
}

func (x *ValidationResult) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidationResult) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *ValidationResult) GetValidatedAgainstVersion() string {
	if x != nil {
		return x.ValidatedAgainstVersion
	}
	return ""
}

func (x *ValidationResult) GetValidatedAgainstHash() string {
	if x != nil {
		return x.ValidatedAgainstHash
	}
	return ""
}

// Breaking change detected between schema versions
type BreakingChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          BreakingChangeType     `protobuf:"varint,1,opt,name=type,proto3,enum=cvt.BreakingChangeType" json:"type,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`                         // API path affected (e.g., "/users/{id}")
	Method        string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`                     // HTTP method affected (e.g., "POST")
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`           // Human-readable description
	OldValue      string                 `protobuf:"bytes,5,opt,name=old_value,json=oldValue,proto3" json:"old_value,omitempty"` // Previous value (for context)
	NewValue      string                 `protobuf:"bytes,6,opt,name=new_value,json=newValue,proto3" json:"new_value,omitempty"` // New value (for context)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BreakingChange) Reset() {
	*x = BreakingChange{}
	mi := &file_api_protos_cvt_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BreakingChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BreakingChange) ProtoMessage() {}

func (x *BreakingChange) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_cvt_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BreakingChange.ProtoReflect.Descriptor instead.
func (*BreakingChange) Descriptor() ([]byte, []int) {
	return file_api_protos_cvt_proto_rawDescGZIP(), []int{8}
}

func (x *BreakingChange) GetType() BreakingChangeType {
	if x != nil {
		return x.Type
	}
	return BreakingChangeType_BREAKING_CHANGE_UNSPECIFIED
}

func (x *BreakingChange) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *BreakingChange) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *BreakingChange) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *BreakingChange) GetOldValue() string {
	if x != nil {
		return x.OldValue
	}
	return ""
}

func (x *BreakingChange) GetNewValue() string {
	if x != nil {
		return x.NewValue
	}
	return ""
}

// Request to get a specific schema
type GetSchemaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaId      string                 `protobuf:"bytes,1,opt,name=schema_id,json=schemaId,proto3" json:"schema_id,omitempty"`
	SchemaVersion string                 `protobuf:"bytes,2,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"` // Optional: specific version (empty = latest)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSchemaRequest) Reset() {
	*x = GetSchemaRequest{}
	mi := &file_api_protos_cvt_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSchemaRequest) ProtoMessage() {}

func (x *GetSchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_cvt_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSchemaRequest.ProtoReflect.Descriptor instead.
func (*GetSchemaRequest) Descriptor() ([]byte, []int) {
	return file_api_protos_cvt_proto_rawDescGZIP(), []int{9}
}

func (x *GetSchemaRequest) GetSchemaId() string {
	if x != nil {
		return x.SchemaId
	}
	return ""
}

func (x *GetSchemaRequest) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

type GetSchemaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Metadata      *SchemaMetadata        `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	SchemaContent string                 `protobuf:"bytes,3,opt,name=schema_content,json=schemaContent,proto3" json:"schema_content,omitempty"` // The actual schema content
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSchemaResponse) Reset() {
	*x = GetSchemaResponse{}
	mi := &file_api_protos_cvt_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSchemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSchemaResponse) ProtoMessage() {}

func (x *GetSchemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_cvt_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSchemaResponse.ProtoReflect.Descriptor instead.
func (*GetSchemaResponse) Descriptor() ([]byte, []int) {
	return file_api_protos_cvt_proto_rawDescGZIP(), []int{10}
}

func (x *GetSchemaResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetSchemaResponse) GetMetadata() *SchemaMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *GetSchemaResponse) GetSchemaContent() string {
	if x != nil {
		return x.SchemaContent
	}
	return ""
}

// Request to list all schemas
type ListSchemasRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`   // Max results per page (default 100)
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"` // Token for pagination
	Owner         string                 `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`                          // Optional: filter by owner
	Team          string                 `protobuf:"bytes,4,opt,name=team,proto3" json:"team,omitempty"`                            // Optional: filter by team
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSchemasRequest) Reset() {
	*x = ListSchemasRequest{}
	mi := &file_api_protos_cvt_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSchemasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSchemasRequest) ProtoMessage() {}

func (x *ListSchemasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_cvt_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSchemasRequest.ProtoReflect.Descriptor instead.
func (*ListSchemasRequest) Descriptor() ([]byte, []int) {
	return file_api_protos_cvt_proto_rawDescGZIP(), []int{11}
}

func (x *ListSchemasRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListSchemasRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListSchemasRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *ListSchemasRequest) GetTeam() string {
	if x != nil {
		return x.Team
	}
	return ""
}

type ListSchemasResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schemas       []*SchemaMetadata      `protobuf:"bytes,1,rep,name=schemas,proto3" json:"schemas,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"` // Token for next page (empty if no more)
	TotalCount    int32                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`           // Total number of schemas matching filter
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSchemasResponse) Reset() {
	*x = ListSchemasResponse{}
	mi := &file_api_protos_cvt_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSchemasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSchemasResponse) ProtoMessage() {}

func (x *ListSchemasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_cvt_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSchemasResponse.ProtoReflect.Descriptor instead.
func (*ListSchemasResponse) Descriptor() ([]byte, []int) {
	return file_api_protos_cvt_proto_rawDescGZIP(), []int{12}
}

func (x *ListSchemasResponse) GetSchemas() []*SchemaMetadata {
	if x != nil {
		return x.Schemas
	}
	return nil
}

func (x *ListSchemasResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListSchemasResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// Request to compare two schema versions
type CompareSchemasRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaId      string                 `protobuf:"bytes,1,opt,name=schema_id,json=schemaId,proto3" json:"schema_id,omitempty"`
	OldVersion    string                 `protobuf:"bytes,2,opt,name=old_version,json=oldVersion,proto3" json:"old_version,omitempty"` // Version to compare from (empty = previous)
	NewVersion    string                 `protobuf:"bytes,3,opt,name=new_version,json=newVersion,proto3" json:"new_version,omitempty"` // Version to compare to (empty = latest)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompareSchemasRequest) Reset() {
	*x = CompareSchemasRequest{}
	mi := &file_api_protos_cvt_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompareSchemasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompareSchemasRequest) ProtoMessage() {}

func (x *CompareSchemasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_cvt_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompareSchemasRequest.ProtoReflect.Descriptor instead.
func (*CompareSchemasRequest) Descriptor() ([]byte, []int) {
	return file_api_protos_cvt_proto_rawDescGZIP(), []int{13}
}

func (x *CompareSchemasRequest) GetSchemaId() string {
	if x != nil {
		return x.SchemaId
	}
	return ""
}

func (x *CompareSchemasRequest) GetOldVersion() string {
	if x != nil {
		return x.OldVersion
	}
	return ""
}

func (x *CompareSchemasRequest) GetNewVersion() string {
	if x != nil {
		return x.NewVersion
	}
	return ""
}

type CompareSchemasResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Compatible      bool                   `protobuf:"varint,1,opt,name=compatible,proto3" json:"compatible,omitempty"` // True if no breaking changes
	BreakingChanges []*BreakingChange      `protobuf:"bytes,2,rep,name=breaking_changes,json=breakingChanges,proto3" json:"breaking_changes,omitempty"`
	OldSchema       *SchemaMetadata        `protobuf:"bytes,3,opt,name=old_schema,json=oldSchema,proto3" json:"old_schema,omitempty"`
	NewSchema       *SchemaMetadata        `protobuf:"bytes,4,opt,name=new_schema,json=newSchema,proto3" json:"new_schema,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CompareSchemasResponse) Reset() {
	*x = CompareSchemasResponse{}
	mi := &file_api_protos_cvt_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompareSchemasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompareSchemasResponse) ProtoMessage() {}

func (x *CompareSchemasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_cvt_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompareSchemasResponse.ProtoReflect.Descriptor instead.
func (*CompareSchemasResponse) Descriptor() ([]byte, []int) {
	return file_api_protos_cvt_proto_rawDescGZIP(), []int{14}
}

func (x *CompareSchemasResponse) GetCompatible() bool {
	if x != nil {
		return x.Compatible
	}
	return false
}

func (x *CompareSchemasResponse) GetBreakingChanges() []*BreakingChange {
	if x != nil {
		return x.BreakingChanges
	}
	return nil
}

func (x *CompareSchemasResponse) GetOldSchema() *SchemaMetadata {
	if x != nil {
		return x.OldSchema
	}
	return nil
}

func (x *CompareSchemasResponse) GetNewSchema() *SchemaMetadata {
	if x != nil {
		return x.NewSchema
	}
	return nil
}

// Request to generate test fixtures
type GenerateFixtureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaId      string                 `protobuf:"bytes,1,opt,name=schema_id,json=schemaId,proto3" json:"schema_id,omitempty"`                            // Schema to generate fixtures from
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`                                                // HTTP method (GET, POST, etc.)
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`                                                    // API path (e.g., /users/{id})
	StatusCode    int32                  `protobuf:"varint,4,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`                     // Response status code (0 = auto-select)
	UseExamples   bool                   `protobuf:"varint,5,opt,name=use_examples,json=useExamples,proto3" json:"use_examples,omitempty"`                  // Use schema examples when available
	ContentType   string                 `protobuf:"bytes,6,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`                   // Content type (default: application/json)
	OutputType    OutputType             `protobuf:"varint,7,opt,name=output_type,json=outputType,proto3,enum=cvt.OutputType" json:"output_type,omitempty"` // What to generate
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateFixtureRequest) Reset() {
	*x = GenerateFixtureRequest{}
	mi := &file_api_protos_cvt_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateFixtureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateFixtureRequest) ProtoMessage() {}

func (x *GenerateFixtureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_cvt_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateFixtureRequest.ProtoReflect.Descriptor instead.
func (*GenerateFixtureRequest) Descriptor() ([]byte, []int) {
	return file_api_protos_cvt_proto_rawDescGZIP(), []int{15}
}

func (x *GenerateFixtureRequest) GetSchemaId() string {
	if x != nil {
		return x.SchemaId
	}
	return ""
}

func (x *GenerateFixtureRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *GenerateFixtureRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *GenerateFixtureRequest) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *GenerateFixtureRequest) GetUseExamples() bool {
	if x != nil {
		return x.UseExamples
	}
	return false
}

func (x *GenerateFixtureRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *GenerateFixtureRequest) GetOutputType() OutputType {
	if x != nil {
		return x.OutputType
	}
	return OutputType_OUTPUT_FIXTURE
}

type GenerateFixtureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Fixture       *GeneratedFixture      `protobuf:"bytes,3,opt,name=fixture,proto3" json:"fixture,omitempty"`                            // Full fixture (if output_type = FIXTURE)
	RequestBody   string                 `protobuf:"bytes,4,opt,name=request_body,json=requestBody,proto3" json:"request_body,omitempty"` // Request body JSON (if output_type = REQUEST)
	Response      *GeneratedResponse     `protobuf:"bytes,5,opt,name=response,proto3" json:"response,omitempty"`                          // Response (if output_type = RESPONSE)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateFixtureResponse) Reset() {
	*x = GenerateFixtureResponse{}
	mi := &file_api_protos_cvt_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateFixtureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateFixtureResponse) ProtoMessage() {}

func (x *GenerateFixtureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_cvt_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateFixtureResponse.ProtoReflect.Descriptor instead.
func (*GenerateFixtureResponse) Descriptor() ([]byte, []int) {
	return file_api_protos_cvt_proto_rawDescGZIP(), []int{16}
}

func (x *GenerateFixtureResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GenerateFixtureResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GenerateFixtureResponse) GetFixture() *GeneratedFixture {
	if x != nil {
		return x.Fixture
	}
	return nil
}

func (x *GenerateFixtureResponse) GetRequestBody() string {
	if x != nil {
		return x.RequestBody
	}
	return ""
}

func (x *GenerateFixtureResponse) GetResponse() *GeneratedResponse {
	if x != nil {
		return x.Response
	}
	return nil
}

type GeneratedFixture struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Request       *GeneratedRequest      `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	Response      *GeneratedResponse     `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeneratedFixture) Reset() {
	*x = GeneratedFixture{}
	mi := &file_api_protos_cvt_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneratedFixture) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneratedFixture) ProtoMessage() {}

func (x *GeneratedFixture) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_cvt_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneratedFixture.ProtoReflect.Descriptor instead.
func (*GeneratedFixture) Descriptor() ([]byte, []int) {
	return file_api_protos_cvt_proto_rawDescGZIP(), []int{17}
}

func (x *GeneratedFixture) GetRequest() *GeneratedRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *GeneratedFixture) GetResponse() *GeneratedResponse {
	if x != nil {
		return x.Response
	}
	return nil
}

type GeneratedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          string                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"` // JSON body as string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeneratedRequest) Reset() {
	*x = GeneratedRequest{}
	mi := &file_api_protos_cvt_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneratedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneratedRequest) ProtoMessage() {}

func (x *GeneratedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_cvt_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneratedRequest.ProtoReflect.Descriptor instead.
func (*GeneratedRequest) Descriptor() ([]byte, []int) {
	return file_api_protos_cvt_proto_rawDescGZIP(), []int{18}
}

func (x *GeneratedRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *GeneratedRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *GeneratedRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *GeneratedRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type GeneratedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"` // JSON body as string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeneratedResponse) Reset() {
	*x = GeneratedResponse{}
	mi := &file_api_protos_cvt_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneratedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneratedResponse) ProtoMessage() {}

func (x *GeneratedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_cvt_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneratedResponse.ProtoReflect.Descriptor instead.
func (*GeneratedResponse) Descriptor() ([]byte, []int) {
	return file_api_protos_cvt_proto_rawDescGZIP(), []int{19}
}

func (x *GeneratedResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *GeneratedResponse) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *GeneratedResponse) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

// Request to list endpoints in a schema
type ListEndpointsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaId      string                 `protobuf:"bytes,1,opt,name=schema_id,json=schemaId,proto3" json:"schema_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEndpointsRequest) Reset() {
	*x = ListEndpointsRequest{}
	mi := &file_api_protos_cvt_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEndpointsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEndpointsRequest) ProtoMessage() {}

func (x *ListEndpointsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_cvt_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEndpointsRequest.ProtoReflect.Descriptor instead.
func (*ListEndpointsRequest) Descriptor() ([]byte, []int) {
	return file_api_protos_cvt_proto_rawDescGZIP(), []int{20}
}

func (x *ListEndpointsRequest) GetSchemaId() string {
	if x != nil {
		return x.SchemaId
	}
	return ""
}

type ListEndpointsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoints     []*EndpointInfo        `protobuf:"bytes,1,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEndpointsResponse) Reset() {
	*x = ListEndpointsResponse{}
	mi := &file_api_protos_cvt_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEndpointsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEndpointsResponse) ProtoMessage() {}

func (x *ListEndpointsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_cvt_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEndpointsResponse.ProtoReflect.Descriptor instead.
func (*ListEndpointsResponse) Descriptor() ([]byte, []int) {
	return file_api_protos_cvt_proto_rawDescGZIP(), []int{21}
}

func (x *ListEndpointsResponse) GetEndpoints() []*EndpointInfo {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

type EndpointInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`                              // HTTP method
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`                                  // API path
	OperationId   string                 `protobuf:"bytes,3,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"` // OpenAPI operationId (if defined)
	Summary       string                 `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"`                            // OpenAPI summary (if defined)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndpointInfo) Reset() {
	*x = EndpointInfo{}
	mi := &file_api_protos_cvt_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndpointInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointInfo) ProtoMessage() {}

func (x *EndpointInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_cvt_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointInfo.ProtoReflect.Descriptor instead.
func (*EndpointInfo) Descriptor() ([]byte, []int) {
	return file_api_protos_cvt_proto_rawDescGZIP(), []int{22}
}

func (x *EndpointInfo) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *EndpointInfo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *EndpointInfo) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *EndpointInfo) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

// Request to validate a producer's response against its OpenAPI schema
type ValidateProducerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaId      string                 `protobuf:"bytes,1,opt,name=schema_id,json=schemaId,proto3" json:"schema_id,omitempty"`                // Schema to validate against
	SchemaVersion string                 `protobuf:"bytes,2,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"` // Optional: specific schema version
	Method        string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`                                    // HTTP method (GET, POST, etc.)
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`                                        // API path with actual values (e.g., /users/123)
	Response      *ResponseData          `protobuf:"bytes,5,opt,name=response,proto3" json:"response,omitempty"`                                // The response to validate
	Request       *RequestData           `protobuf:"bytes,6,opt,name=request,proto3" json:"request,omitempty"`                                  // Optional: request context (for path param extraction)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateProducerRequest) Reset() {
	*x = ValidateProducerRequest{}
	mi := &file_api_protos_cvt_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateProducerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateProducerRequest) ProtoMessage() {}

func (x *ValidateProducerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_cvt_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateProducerRequest.ProtoReflect.Descriptor instead.
func (*ValidateProducerRequest) Descriptor() ([]byte, []int) {
	return file_api_protos_cvt_proto_rawDescGZIP(), []int{23}
}

func (x *ValidateProducerRequest) GetSchemaId() string {
	if x != nil {
		return x.SchemaId
	}
	return ""
}

func (x *ValidateProducerRequest) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *ValidateProducerRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *ValidateProducerRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ValidateProducerRequest) GetResponse() *ResponseData {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *ValidateProducerRequest) GetRequest() *RequestData {
	if x != nil {
		return x.Request
	}
	return nil
}

// Information about a consumer's dependency on a schema
type ConsumerInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ConsumerId      string                 `protobuf:"bytes,1,opt,name=consumer_id,json=consumerId,proto3" json:"consumer_id,omitempty"`                   // Unique consumer identifier (e.g., "order-service")
	ConsumerVersion string                 `protobuf:"bytes,2,opt,name=consumer_version,json=consumerVersion,proto3" json:"consumer_version,omitempty"`    // Consumer's version (e.g., "2.1.0")
	SchemaId        string                 `protobuf:"bytes,3,opt,name=schema_id,json=schemaId,proto3" json:"schema_id,omitempty"`                         // Schema this consumer depends on
	SchemaVersion   string                 `protobuf:"bytes,4,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`          // Schema version consumer was tested against
	Environment     string                 `protobuf:"bytes,5,opt,name=environment,proto3" json:"environment,omitempty"`                                   // Environment (dev, staging, prod)
	RegisteredAt    int64                  `protobuf:"varint,6,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`            // Unix timestamp of registration
	LastValidatedAt int64                  `protobuf:"varint,7,opt,name=last_validated_at,json=lastValidatedAt,proto3" json:"last_validated_at,omitempty"` // Unix timestamp of last successful validation
	UsedEndpoints   []*EndpointUsage       `protobuf:"bytes,8,rep,name=used_endpoints,json=usedEndpoints,proto3" json:"used_endpoints,omitempty"`          // Which endpoints the consumer uses
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ConsumerInfo) Reset() {
	*x = ConsumerInfo{}
	mi := &file_api_protos_cvt_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumerInfo) ProtoMessage() {}

func (x *ConsumerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_cvt_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumerInfo.ProtoReflect.Descriptor instead.
func (*ConsumerInfo) Descriptor() ([]byte, []int) {
	return file_api_protos_cvt_proto_rawDescGZIP(), []int{24}
}

func (x *ConsumerInfo) GetConsumerId() string {
	if x != nil {
		return x.ConsumerId
	}
	return ""
}

func (x *ConsumerInfo) GetConsumerVersion() string {
	if x != nil {
		return x.ConsumerVersion
	}
	return ""
}

func (x *ConsumerInfo) GetSchemaId() string {
	if x != nil {
		return x.SchemaId
	}
	return ""
}

func (x *ConsumerInfo) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *ConsumerInfo) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *ConsumerInfo) GetRegisteredAt() int64 {
	if x != nil {
		return x.RegisteredAt
	}
	return 0
}

func (x *ConsumerInfo) GetLastValidatedAt() int64 {
	if x != nil {
		return x.LastValidatedAt
	}
	return 0
}

func (x *ConsumerInfo) GetUsedEndpoints() []*EndpointUsage {
	if x != nil {
		return x.UsedEndpoints
	}
	return nil
}

// Describes which endpoints and fields a consumer uses
type EndpointUsage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`                           // HTTP method
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`                               // API path
	UsedFields    []string               `protobuf:"bytes,3,rep,name=used_fields,json=usedFields,proto3" json:"used_fields,omitempty"` // Fields used in response (e.g., ["email", "name"])
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndpointUsage) Reset() {
	*x = EndpointUsage{}
	mi := &file_api_protos_cvt_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndpointUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointUsage) ProtoMessage() {}

func (x *EndpointUsage) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_cvt_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointUsage.ProtoReflect.Descriptor instead.
func (*EndpointUsage) Descriptor() ([]byte, []int) {
	return file_api_protos_cvt_proto_rawDescGZIP(), []int{25}
}

func (x *EndpointUsage) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *EndpointUsage) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *EndpointUsage) GetUsedFields() []string {
	if x != nil {
		return x.UsedFields
	}
	return nil
}

// Request to register a consumer's dependency
type RegisterConsumerRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ConsumerId      string                 `protobuf:"bytes,1,opt,name=consumer_id,json=consumerId,proto3" json:"consumer_id,omitempty"`
	ConsumerVersion string                 `protobuf:"bytes,2,opt,name=consumer_version,json=consumerVersion,proto3" json:"consumer_version,omitempty"`
	SchemaId        string                 `protobuf:"bytes,3,opt,name=schema_id,json=schemaId,proto3" json:"schema_id,omitempty"`
	SchemaVersion   string                 `protobuf:"bytes,4,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	Environment     string                 `protobuf:"bytes,5,opt,name=environment,proto3" json:"environment,omitempty"`
	UsedEndpoints   []*EndpointUsage       `protobuf:"bytes,6,rep,name=used_endpoints,json=usedEndpoints,proto3" json:"used_endpoints,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RegisterConsumerRequest) Reset() {
	*x = RegisterConsumerRequest{}
	mi := &file_api_protos_cvt_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterConsumerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterConsumerRequest) ProtoMessage() {}

func (x *RegisterConsumerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_cvt_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterConsumerRequest.ProtoReflect.Descriptor instead.
func (*RegisterConsumerRequest) Descriptor() ([]byte, []int) {
	return file_api_protos_cvt_proto_rawDescGZIP(), []int{26}
}

func (x *RegisterConsumerRequest) GetConsumerId() string {
	if x != nil {
		return x.ConsumerId
	}
	return ""
}

func (x *RegisterConsumerRequest) GetConsumerVersion() string {
	if x != nil {
		return x.ConsumerVersion
	}
	return ""
}

func (x *RegisterConsumerRequest) GetSchemaId() string {
	if x != nil {
		return x.SchemaId
	}
	return ""
}

func (x *RegisterConsumerRequest) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *RegisterConsumerRequest) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *RegisterConsumerRequest) GetUsedEndpoints() []*EndpointUsage {
	if x != nil {
		return x.UsedEndpoints
	}
	return nil
}

// Response from consumer registration
type RegisterConsumerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Consumer      *ConsumerInfo          `protobuf:"bytes,3,opt,name=consumer,proto3" json:"consumer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterConsumerResponse) Reset() {
	*x = RegisterConsumerResponse{}
	mi := &file_api_protos_cvt_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterConsumerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterConsumerResponse) ProtoMessage() {}

func (x *RegisterConsumerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_cvt_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterConsumerResponse.ProtoReflect.Descriptor instead.
func (*RegisterConsumerResponse) Descriptor() ([]byte, []int) {
	return file_api_protos_cvt_proto_rawDescGZIP(), []int{27}
}

func (x *RegisterConsumerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterConsumerResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterConsumerResponse) GetConsumer() *ConsumerInfo {
	if x != nil {
		return x.Consumer
	}
	return nil
}

// Request to list consumers of a schema
type ListConsumersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaId      string                 `protobuf:"bytes,1,opt,name=schema_id,json=schemaId,proto3" json:"schema_id,omitempty"` // Required: schema to query
	Environment   string                 `protobuf:"bytes,2,opt,name=environment,proto3" json:"environment,omitempty"`           // Optional: filter by environment
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConsumersRequest) Reset() {
	*x = ListConsumersRequest{}
	mi := &file_api_protos_cvt_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConsumersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConsumersRequest) ProtoMessage() {}

func (x *ListConsumersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_cvt_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConsumersRequest.ProtoReflect.Descriptor instead.
func (*ListConsumersRequest) Descriptor() ([]byte, []int) {
	return file_api_protos_cvt_proto_rawDescGZIP(), []int{28}
}

func (x *ListConsumersRequest) GetSchemaId() string {
	if x != nil {
		return x.SchemaId
	}
	return ""
}

func (x *ListConsumersRequest) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

// Response containing list of consumers
type ListConsumersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Consumers     []*ConsumerInfo        `protobuf:"bytes,1,rep,name=consumers,proto3" json:"consumers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConsumersResponse) Reset() {
	*x = ListConsumersResponse{}
	mi := &file_api_protos_cvt_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConsumersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConsumersResponse) ProtoMessage() {}

func (x *ListConsumersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_cvt_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConsumersResponse.ProtoReflect.Descriptor instead.
func (*ListConsumersResponse) Descriptor() ([]byte, []int) {
	return file_api_protos_cvt_proto_rawDescGZIP(), []int{29}
}

func (x *ListConsumersResponse) GetConsumers() []*ConsumerInfo {
	if x != nil {
		return x.Consumers
	}
	return nil
}

// Request to remove a consumer registration
type DeregisterConsumerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConsumerId    string                 `protobuf:"bytes,1,opt,name=consumer_id,json=consumerId,proto3" json:"consumer_id,omitempty"`
	SchemaId      string                 `protobuf:"bytes,2,opt,name=schema_id,json=schemaId,proto3" json:"schema_id,omitempty"` // Required: which schema dependency to remove
	Environment   string                 `protobuf:"bytes,3,opt,name=environment,proto3" json:"environment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterConsumerRequest) Reset() {
	*x = DeregisterConsumerRequest{}
	mi := &file_api_protos_cvt_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterConsumerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterConsumerRequest) ProtoMessage() {}

func (x *DeregisterConsumerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_cvt_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterConsumerRequest.ProtoReflect.Descriptor instead.
func (*DeregisterConsumerRequest) Descriptor() ([]byte, []int) {
	return file_api_protos_cvt_proto_rawDescGZIP(), []int{30}
}

func (x *DeregisterConsumerRequest) GetConsumerId() string {
	if x != nil {
		return x.ConsumerId
	}
	return ""
}

func (x *DeregisterConsumerRequest) GetSchemaId() string {
	if x != nil {
		return x.SchemaId
	}
	return ""
}

func (x *DeregisterConsumerRequest) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

// Response from consumer deregistration
type DeregisterConsumerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterConsumerResponse) Reset() {
	*x = DeregisterConsumerResponse{}
	mi := &file_api_protos_cvt_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterConsumerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterConsumerResponse) ProtoMessage() {}

func (x *DeregisterConsumerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_cvt_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterConsumerResponse.ProtoReflect.Descriptor instead.
func (*DeregisterConsumerResponse) Descriptor() ([]byte, []int) {
	return file_api_protos_cvt_proto_rawDescGZIP(), []int{31}
}

func (x *DeregisterConsumerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeregisterConsumerResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Request to check deployment safety
type CanIDeployRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaId      string                 `protobuf:"bytes,1,opt,name=schema_id,json=schemaId,proto3" json:"schema_id,omitempty"`       // Schema to deploy
	NewVersion    string                 `protobuf:"bytes,2,opt,name=new_version,json=newVersion,proto3" json:"new_version,omitempty"` // New version to deploy
	Environment   string                 `protobuf:"bytes,3,opt,name=environment,proto3" json:"environment,omitempty"`                 // Target environment (dev, staging, prod)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CanIDeployRequest) Reset() {
	*x = CanIDeployRequest{}
	mi := &file_api_protos_cvt_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CanIDeployRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CanIDeployRequest) ProtoMessage() {}

func (x *CanIDeployRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_cvt_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CanIDeployRequest.ProtoReflect.Descriptor instead.
func (*CanIDeployRequest) Descriptor() ([]byte, []int) {
	return file_api_protos_cvt_proto_rawDescGZIP(), []int{32}
}

func (x *CanIDeployRequest) GetSchemaId() string {
	if x != nil {
		return x.SchemaId
	}
	return ""
}

func (x *CanIDeployRequest) GetNewVersion() string {
	if x != nil {
		return x.NewVersion
	}
	return ""
}

func (x *CanIDeployRequest) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

// Response with deployment safety analysis
type CanIDeployResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SafeToDeploy      bool                   `protobuf:"varint,1,opt,name=safe_to_deploy,json=safeToDeploy,proto3" json:"safe_to_deploy,omitempty"`             // True if safe to deploy
	Summary           string                 `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`                                              // Human-readable summary
	BreakingChanges   []*BreakingChange      `protobuf:"bytes,3,rep,name=breaking_changes,json=breakingChanges,proto3" json:"breaking_changes,omitempty"`       // All breaking changes in new version
	AffectedConsumers []*ConsumerImpact      `protobuf:"bytes,4,rep,name=affected_consumers,json=affectedConsumers,proto3" json:"affected_consumers,omitempty"` // Impact on each consumer
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CanIDeployResponse) Reset() {
	*x = CanIDeployResponse{}
	mi := &file_api_protos_cvt_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CanIDeployResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CanIDeployResponse) ProtoMessage() {}

func (x *CanIDeployResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_cvt_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CanIDeployResponse.ProtoReflect.Descriptor instead.
func (*CanIDeployResponse) Descriptor() ([]byte, []int) {
	return file_api_protos_cvt_proto_rawDescGZIP(), []int{33}
}

func (x *CanIDeployResponse) GetSafeToDeploy() bool {
	if x != nil {
		return x.SafeToDeploy
	}
	return false
}

func (x *CanIDeployResponse) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *CanIDeployResponse) GetBreakingChanges() []*BreakingChange {
	if x != nil {
		return x.BreakingChanges
	}
	return nil
}

func (x *CanIDeployResponse) GetAffectedConsumers() []*ConsumerImpact {
	if x != nil {
		return x.AffectedConsumers
	}
	return nil
}

// Impact of schema changes on a specific consumer
type ConsumerImpact struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ConsumerId           string                 `protobuf:"bytes,1,opt,name=consumer_id,json=consumerId,proto3" json:"consumer_id,omitempty"`
	ConsumerVersion      string                 `protobuf:"bytes,2,opt,name=consumer_version,json=consumerVersion,proto3" json:"consumer_version,omitempty"`
	CurrentSchemaVersion string                 `protobuf:"bytes,3,opt,name=current_schema_version,json=currentSchemaVersion,proto3" json:"current_schema_version,omitempty"` // Version consumer was tested against
	Environment          string                 `protobuf:"bytes,4,opt,name=environment,proto3" json:"environment,omitempty"`
	WillBreak            bool                   `protobuf:"varint,5,opt,name=will_break,json=willBreak,proto3" json:"will_break,omitempty"`                  // True if consumer will be affected
	RelevantChanges      []*BreakingChange      `protobuf:"bytes,6,rep,name=relevant_changes,json=relevantChanges,proto3" json:"relevant_changes,omitempty"` // Breaking changes affecting this consumer
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ConsumerImpact) Reset() {
	*x = ConsumerImpact{}
	mi := &file_api_protos_cvt_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumerImpact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumerImpact) ProtoMessage() {}

func (x *ConsumerImpact) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_cvt_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumerImpact.ProtoReflect.Descriptor instead.
func (*ConsumerImpact) Descriptor() ([]byte, []int) {
	return file_api_protos_cvt_proto_rawDescGZIP(), []int{34}
}

func (x *ConsumerImpact) GetConsumerId() string {
	if x != nil {
		return x.ConsumerId
	}
	return ""
}

func (x *ConsumerImpact) GetConsumerVersion() string {
	if x != nil {
		return x.ConsumerVersion
	}
	return ""
}

func (x *ConsumerImpact) GetCurrentSchemaVersion() string {
	if x != nil {
		return x.CurrentSchemaVersion
	}
	return ""
}

func (x *ConsumerImpact) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *ConsumerImpact) GetWillBreak() bool {
	if x != nil {
		return x.WillBreak
	}
	return false
}

func (x *ConsumerImpact) GetRelevantChanges() []*BreakingChange {
	if x != nil {
		return x.RelevantChanges
	}
	return nil
}

var File_api_protos_cvt_proto protoreflect.FileDescriptor

const file_api_protos_cvt_proto_rawDesc = "" +
	"\n" +
	"\x14api/protos/cvt.proto\x12\x03cvt\"}\n" +
	"\x0fSchemaOwnership\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x12\n" +
	"\x04team\x18\x02 \x01(\tR\x04team\x12#\n" +
	"\rcontact_email\x18\x03 \x01(\tR\fcontactEmail\x12\x1b\n" +
	"\tread_only\x18\x04 \x01(\bR\breadOnly\"\xbd\x02\n" +
	"\x0eSchemaMetadata\x12\x1b\n" +
	"\tschema_id\x18\x01 \x01(\tR\bschemaId\x12%\n" +
	"\x0eschema_version\x18\x02 \x01(\tR\rschemaVersion\x12\x1f\n" +
	"\vschema_hash\x18\x03 \x01(\tR\n" +
	"schemaHash\x12#\n" +
	"\rregistered_at\x18\x04 \x01(\x03R\fregisteredAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\x03R\tupdatedAt\x122\n" +
	"\townership\x18\x06 \x01(\v2\x14.cvt.SchemaOwnershipR\townership\x12'\n" +
	"\x0fopenapi_version\x18\a \x01(\tR\x0eopenapiVersion\x12%\n" +
	"\x0eendpoint_count\x18\b \x01(\x05R\rendpointCount\"\xe7\x01\n" +
	"\x15RegisterSchemaRequest\x12\x1b\n" +
	"\tschema_id\x18\x01 \x01(\tR\bschemaId\x12%\n" +
	"\x0eschema_content\x18\x02 \x01(\tR\rschemaContent\x12%\n" +
	"\x0eschema_version\x18\x03 \x01(\tR\rschemaVersion\x122\n" +
	"\townership\x18\x04 \x01(\v2\x14.cvt.SchemaOwnershipR\townership\x12/\n" +
	"\x13check_compatibility\x18\x05 \x01(\bR\x12checkCompatibility\"\xbd\x01\n" +
	"\x16RegisterSchemaResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12/\n" +
	"\bmetadata\x18\x03 \x01(\v2\x13.cvt.SchemaMetadataR\bmetadata\x12>\n" +
	"\x10breaking_changes\x18\x04 \x03(\v2\x13.cvt.BreakingChangeR\x0fbreakingChanges\"\xb3\x01\n" +
	"\x12InteractionRequest\x12\x1b\n" +
	"\tschema_id\x18\x01 \x01(\tR\bschemaId\x12*\n" +
	"\arequest\x18\x02 \x01(\v2\x10.cvt.RequestDataR\arequest\x12-\n" +
	"\bresponse\x18\x03 \x01(\v2\x11.cvt.ResponseDataR\bresponse\x12%\n" +
	"\x0eschema_version\x18\x04 \x01(\tR\rschemaVersion\"\xc2\x01\n" +
	"\vRequestData\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x127\n" +
	"\aheaders\x18\x03 \x03(\v2\x1d.cvt.RequestData.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb9\x01\n" +
	"\fResponseData\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x128\n" +
	"\aheaders\x18\x02 \x03(\v2\x1e.cvt.ResponseData.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb2\x01\n" +
	"\x10ValidationResult\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x16\n" +
	"\x06errors\x18\x02 \x03(\tR\x06errors\x12:\n" +
	"\x19validated_against_version\x18\x03 \x01(\tR\x17validatedAgainstVersion\x124\n" +
	"\x16validated_against_hash\x18\x04 \x01(\tR\x14validatedAgainstHash\"\xc5\x01\n" +
	"\x0eBreakingChange\x12+\n" +
	"\x04type\x18\x01 \x01(\x0e2\x17.cvt.BreakingChangeTypeR\x04type\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1b\n" +
	"\told_value\x18\x05 \x01(\tR\boldValue\x12\x1b\n" +
	"\tnew_value\x18\x06 \x01(\tR\bnewValue\"V\n" +
	"\x10GetSchemaRequest\x12\x1b\n" +
	"\tschema_id\x18\x01 \x01(\tR\bschemaId\x12%\n" +
	"\x0eschema_version\x18\x02 \x01(\tR\rschemaVersion\"\x81\x01\n" +
	"\x11GetSchemaResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12/\n" +
	"\bmetadata\x18\x02 \x01(\v2\x13.cvt.SchemaMetadataR\bmetadata\x12%\n" +
	"\x0eschema_content\x18\x03 \x01(\tR\rschemaContent\"z\n" +
	"\x12ListSchemasRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12\x14\n" +
	"\x05owner\x18\x03 \x01(\tR\x05owner\x12\x12\n" +
	"\x04team\x18\x04 \x01(\tR\x04team\"\x8d\x01\n" +
	"\x13ListSchemasResponse\x12-\n" +
	"\aschemas\x18\x01 \x03(\v2\x13.cvt.SchemaMetadataR\aschemas\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\"v\n" +
	"\x15CompareSchemasRequest\x12\x1b\n" +
	"\tschema_id\x18\x01 \x01(\tR\bschemaId\x12\x1f\n" +
	"\vold_version\x18\x02 \x01(\tR\n" +
	"oldVersion\x12\x1f\n" +
	"\vnew_version\x18\x03 \x01(\tR\n" +
	"newVersion\"\xe0\x01\n" +
	"\x16CompareSchemasResponse\x12\x1e\n" +
	"\n" +
	"compatible\x18\x01 \x01(\bR\n" +
	"compatible\x12>\n" +
	"\x10breaking_changes\x18\x02 \x03(\v2\x13.cvt.BreakingChangeR\x0fbreakingChanges\x122\n" +
	"\n" +
	"old_schema\x18\x03 \x01(\v2\x13.cvt.SchemaMetadataR\toldSchema\x122\n" +
	"\n" +
	"new_schema\x18\x04 \x01(\v2\x13.cvt.SchemaMetadataR\tnewSchema\"\xfa\x01\n" +
	"\x16GenerateFixtureRequest\x12\x1b\n" +
	"\tschema_id\x18\x01 \x01(\tR\bschemaId\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x1f\n" +
	"\vstatus_code\x18\x04 \x01(\x05R\n" +
	"statusCode\x12!\n" +
	"\fuse_examples\x18\x05 \x01(\bR\vuseExamples\x12!\n" +
	"\fcontent_type\x18\x06 \x01(\tR\vcontentType\x120\n" +
	"\voutput_type\x18\a \x01(\x0e2\x0f.cvt.OutputTypeR\n" +
	"outputType\"\xd5\x01\n" +
	"\x17GenerateFixtureResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12/\n" +
	"\afixture\x18\x03 \x01(\v2\x15.cvt.GeneratedFixtureR\afixture\x12!\n" +
	"\frequest_body\x18\x04 \x01(\tR\vrequestBody\x122\n" +
	"\bresponse\x18\x05 \x01(\v2\x16.cvt.GeneratedResponseR\bresponse\"w\n" +
	"\x10GeneratedFixture\x12/\n" +
	"\arequest\x18\x01 \x01(\v2\x15.cvt.GeneratedRequestR\arequest\x122\n" +
	"\bresponse\x18\x02 \x01(\v2\x16.cvt.GeneratedResponseR\bresponse\"\xcc\x01\n" +
	"\x10GeneratedRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12<\n" +
	"\aheaders\x18\x03 \x03(\v2\".cvt.GeneratedRequest.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc3\x01\n" +
	"\x11GeneratedResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12=\n" +
	"\aheaders\x18\x02 \x03(\v2#.cvt.GeneratedResponse.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"3\n" +
	"\x14ListEndpointsRequest\x12\x1b\n" +
	"\tschema_id\x18\x01 \x01(\tR\bschemaId\"H\n" +
	"\x15ListEndpointsResponse\x12/\n" +
	"\tendpoints\x18\x01 \x03(\v2\x11.cvt.EndpointInfoR\tendpoints\"w\n" +
	"\fEndpointInfo\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12!\n" +
	"\foperation_id\x18\x03 \x01(\tR\voperationId\x12\x18\n" +
	"\asummary\x18\x04 \x01(\tR\asummary\"\xe4\x01\n" +
	"\x17ValidateProducerRequest\x12\x1b\n" +
	"\tschema_id\x18\x01 \x01(\tR\bschemaId\x12%\n" +
	"\x0eschema_version\x18\x02 \x01(\tR\rschemaVersion\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12-\n" +
	"\bresponse\x18\x05 \x01(\v2\x11.cvt.ResponseDataR\bresponse\x12*\n" +
	"\arequest\x18\x06 \x01(\v2\x10.cvt.RequestDataR\arequest\"\xcc\x02\n" +
	"\fConsumerInfo\x12\x1f\n" +
	"\vconsumer_id\x18\x01 \x01(\tR\n" +
	"consumerId\x12)\n" +
	"\x10consumer_version\x18\x02 \x01(\tR\x0fconsumerVersion\x12\x1b\n" +
	"\tschema_id\x18\x03 \x01(\tR\bschemaId\x12%\n" +
	"\x0eschema_version\x18\x04 \x01(\tR\rschemaVersion\x12 \n" +
	"\venvironment\x18\x05 \x01(\tR\venvironment\x12#\n" +
	"\rregistered_at\x18\x06 \x01(\x03R\fregisteredAt\x12*\n" +
	"\x11last_validated_at\x18\a \x01(\x03R\x0flastValidatedAt\x129\n" +
	"\x0eused_endpoints\x18\b \x03(\v2\x12.cvt.EndpointUsageR\rusedEndpoints\"\\\n" +
	"\rEndpointUsage\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x1f\n" +
	"\vused_fields\x18\x03 \x03(\tR\n" +
	"usedFields\"\x86\x02\n" +
	"\x17RegisterConsumerRequest\x12\x1f\n" +
	"\vconsumer_id\x18\x01 \x01(\tR\n" +
	"consumerId\x12)\n" +
	"\x10consumer_version\x18\x02 \x01(\tR\x0fconsumerVersion\x12\x1b\n" +
	"\tschema_id\x18\x03 \x01(\tR\bschemaId\x12%\n" +
	"\x0eschema_version\x18\x04 \x01(\tR\rschemaVersion\x12 \n" +
	"\venvironment\x18\x05 \x01(\tR\venvironment\x129\n" +
	"\x0eused_endpoints\x18\x06 \x03(\v2\x12.cvt.EndpointUsageR\rusedEndpoints\"}\n" +
	"\x18RegisterConsumerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12-\n" +
	"\bconsumer\x18\x03 \x01(\v2\x11.cvt.ConsumerInfoR\bconsumer\"U\n" +
	"\x14ListConsumersRequest\x12\x1b\n" +
	"\tschema_id\x18\x01 \x01(\tR\bschemaId\x12 \n" +
	"\venvironment\x18\x02 \x01(\tR\venvironment\"H\n" +
	"\x15ListConsumersResponse\x12/\n" +
	"\tconsumers\x18\x01 \x03(\v2\x11.cvt.ConsumerInfoR\tconsumers\"{\n" +
	"\x19DeregisterConsumerRequest\x12\x1f\n" +
	"\vconsumer_id\x18\x01 \x01(\tR\n" +
	"consumerId\x12\x1b\n" +
	"\tschema_id\x18\x02 \x01(\tR\bschemaId\x12 \n" +
	"\venvironment\x18\x03 \x01(\tR\venvironment\"P\n" +
	"\x1aDeregisterConsumerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"s\n" +
	"\x11CanIDeployRequest\x12\x1b\n" +
	"\tschema_id\x18\x01 \x01(\tR\bschemaId\x12\x1f\n" +
	"\vnew_version\x18\x02 \x01(\tR\n" +
	"newVersion\x12 \n" +
	"\venvironment\x18\x03 \x01(\tR\venvironment\"\xd8\x01\n" +
	"\x12CanIDeployResponse\x12$\n" +
	"\x0esafe_to_deploy\x18\x01 \x01(\bR\fsafeToDeploy\x12\x18\n" +
	"\asummary\x18\x02 \x01(\tR\asummary\x12>\n" +
	"\x10breaking_changes\x18\x03 \x03(\v2\x13.cvt.BreakingChangeR\x0fbreakingChanges\x12B\n" +
	"\x12affected_consumers\x18\x04 \x03(\v2\x13.cvt.ConsumerImpactR\x11affectedConsumers\"\x93\x02\n" +
	"\x0eConsumerImpact\x12\x1f\n" +
	"\vconsumer_id\x18\x01 \x01(\tR\n" +
	"consumerId\x12)\n" +
	"\x10consumer_version\x18\x02 \x01(\tR\x0fconsumerVersion\x124\n" +
	"\x16current_schema_version\x18\x03 \x01(\tR\x14currentSchemaVersion\x12 \n" +
	"\venvironment\x18\x04 \x01(\tR\venvironment\x12\x1d\n" +
	"\n" +
	"will_break\x18\x05 \x01(\bR\twillBreak\x12>\n" +
	"\x10relevant_changes\x18\x06 \x03(\v2\x13.cvt.BreakingChangeR\x0frelevantChanges*\xca\x01\n" +
	"\x12BreakingChangeType\x12\x1f\n" +
	"\x1bBREAKING_CHANGE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10ENDPOINT_REMOVED\x10\x01\x12\x18\n" +
	"\x14REQUIRED_FIELD_ADDED\x10\x02\x12\x10\n" +
	"\fTYPE_CHANGED\x10\x03\x12\x1c\n" +
	"\x18REQUIRED_PARAMETER_ADDED\x10\x04\x12\x1b\n" +
	"\x17RESPONSE_SCHEMA_CHANGED\x10\x05\x12\x16\n" +
	"\x12ENUM_VALUE_REMOVED\x10\x06*I\n" +
	"\n" +
	"OutputType\x12\x12\n" +
	"\x0eOUTPUT_FIXTURE\x10\x00\x12\x12\n" +
	"\x0eOUTPUT_REQUEST\x10\x01\x12\x13\n" +
	"\x0fOUTPUT_RESPONSE\x10\x022\x84\a\n" +
	"\x11ContractValidator\x12I\n" +
	"\x0eRegisterSchema\x12\x1a.cvt.RegisterSchemaRequest\x1a\x1b.cvt.RegisterSchemaResponse\x12E\n" +
	"\x13ValidateInteraction\x12\x17.cvt.InteractionRequest\x1a\x15.cvt.ValidationResult\x12:\n" +
	"\tGetSchema\x12\x15.cvt.GetSchemaRequest\x1a\x16.cvt.GetSchemaResponse\x12@\n" +
	"\vListSchemas\x12\x17.cvt.ListSchemasRequest\x1a\x18.cvt.ListSchemasResponse\x12I\n" +
	"\x0eCompareSchemas\x12\x1a.cvt.CompareSchemasRequest\x1a\x1b.cvt.CompareSchemasResponse\x12L\n" +
	"\x0fGenerateFixture\x12\x1b.cvt.GenerateFixtureRequest\x1a\x1c.cvt.GenerateFixtureResponse\x12F\n" +
	"\rListEndpoints\x12\x19.cvt.ListEndpointsRequest\x1a\x1a.cvt.ListEndpointsResponse\x12O\n" +
	"\x18ValidateProducerResponse\x12\x1c.cvt.ValidateProducerRequest\x1a\x15.cvt.ValidationResult\x12O\n" +
	"\x10RegisterConsumer\x12\x1c.cvt.RegisterConsumerRequest\x1a\x1d.cvt.RegisterConsumerResponse\x12F\n" +
	"\rListConsumers\x12\x19.cvt.ListConsumersRequest\x1a\x1a.cvt.ListConsumersResponse\x12U\n" +
	"\x12DeregisterConsumer\x12\x1e.cvt.DeregisterConsumerRequest\x1a\x1f.cvt.DeregisterConsumerResponse\x12=\n" +
	"\n" +
	"CanIDeploy\x12\x16.cvt.CanIDeployRequest\x1a\x17.cvt.CanIDeployResponseB/\n" +
	"\rcom.cvt.protoP\x01Z\x1cgithub.com/cvt/cvt/server/pbb\x06proto3"

var (
	file_api_protos_cvt_proto_rawDescOnce sync.Once
	file_api_protos_cvt_proto_rawDescData []byte
)

func file_api_protos_cvt_proto_rawDescGZIP() []byte {
	file_api_protos_cvt_proto_rawDescOnce.Do(func() {
		file_api_protos_cvt_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_protos_cvt_proto_rawDesc), len(file_api_protos_cvt_proto_rawDesc)))
	})
	return file_api_protos_cvt_proto_rawDescData
}

var file_api_protos_cvt_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_protos_cvt_proto_msgTypes = make([]protoimpl.MessageInfo, 39)
var file_api_protos_cvt_proto_goTypes = []any{
	(BreakingChangeType)(0),            // 0: cvt.BreakingChangeType
	(OutputType)(0),                    // 1: cvt.OutputType
	(*SchemaOwnership)(nil),            // 2: cvt.SchemaOwnership
	(*SchemaMetadata)(nil),             // 3: cvt.SchemaMetadata
	(*RegisterSchemaRequest)(nil),      // 4: cvt.RegisterSchemaRequest
	(*RegisterSchemaResponse)(nil),     // 5: cvt.RegisterSchemaResponse
	(*InteractionRequest)(nil),         // 6: cvt.InteractionRequest
	(*RequestData)(nil),                // 7: cvt.RequestData
	(*ResponseData)(nil),               // 8: cvt.ResponseData
	(*ValidationResult)(nil),           // 9: cvt.ValidationResult
	(*BreakingChange)(nil),             // 10: cvt.BreakingChange
	(*GetSchemaRequest)(nil),           // 11: cvt.GetSchemaRequest
	(*GetSchemaResponse)(nil),          // 12: cvt.GetSchemaResponse
	(*ListSchemasRequest)(nil),         // 13: cvt.ListSchemasRequest
	(*ListSchemasResponse)(nil),        // 14: cvt.ListSchemasResponse
	(*CompareSchemasRequest)(nil),      // 15: cvt.CompareSchemasRequest
	(*CompareSchemasResponse)(nil),     // 16: cvt.CompareSchemasResponse
	(*GenerateFixtureRequest)(nil),     // 17: cvt.GenerateFixtureRequest
	(*GenerateFixtureResponse)(nil),    // 18: cvt.GenerateFixtureResponse
	(*GeneratedFixture)(nil),           // 19: cvt.GeneratedFixture
	(*GeneratedRequest)(nil),           // 20: cvt.GeneratedRequest
	(*GeneratedResponse)(nil),          // 21: cvt.GeneratedResponse
	(*ListEndpointsRequest)(nil),       // 22: cvt.ListEndpointsRequest
	(*ListEndpointsResponse)(nil),      // 23: cvt.ListEndpointsResponse
	(*EndpointInfo)(nil),               // 24: cvt.EndpointInfo
	(*ValidateProducerRequest)(nil),    // 25: cvt.ValidateProducerRequest
	(*ConsumerInfo)(nil),               // 26: cvt.ConsumerInfo
	(*EndpointUsage)(nil),              // 27: cvt.EndpointUsage
	(*RegisterConsumerRequest)(nil),    // 28: cvt.RegisterConsumerRequest
	(*RegisterConsumerResponse)(nil),   // 29: cvt.RegisterConsumerResponse
	(*ListConsumersRequest)(nil),       // 30: cvt.ListConsumersRequest
	(*ListConsumersResponse)(nil),      // 31: cvt.ListConsumersResponse
	(*DeregisterConsumerRequest)(nil),  // 32: cvt.DeregisterConsumerRequest
	(*DeregisterConsumerResponse)(nil), // 33: cvt.DeregisterConsumerResponse
	(*CanIDeployRequest)(nil),          // 34: cvt.CanIDeployRequest
	(*CanIDeployResponse)(nil),         // 35: cvt.CanIDeployResponse
	(*ConsumerImpact)(nil),             // 36: cvt.ConsumerImpact
	nil,                                // 37: cvt.RequestData.HeadersEntry
	nil,                                // 38: cvt.ResponseData.HeadersEntry
	nil,                                // 39: cvt.GeneratedRequest.HeadersEntry
	nil,                                // 40: cvt.GeneratedResponse.HeadersEntry
}
var file_api_protos_cvt_proto_depIdxs = []int32{
	2,  // 0: cvt.SchemaMetadata.ownership:type_name -> cvt.SchemaOwnership
	2,  // 1: cvt.RegisterSchemaRequest.ownership:type_name -> cvt.SchemaOwnership
	3,  // 2: cvt.RegisterSchemaResponse.metadata:type_name -> cvt.SchemaMetadata
	10, // 3: cvt.RegisterSchemaResponse.breaking_changes:type_name -> cvt.BreakingChange
	7,  // 4: cvt.InteractionRequest.request:type_name -> cvt.RequestData
	8,  // 5: cvt.InteractionRequest.response:type_name -> cvt.ResponseData
	37, // 6: cvt.RequestData.headers:type_name -> cvt.RequestData.HeadersEntry
	38, // 7: cvt.ResponseData.headers:type_name -> cvt.ResponseData.HeadersEntry
	0,  // 8: cvt.BreakingChange.type:type_name -> cvt.BreakingChangeType
	3,  // 9: cvt.GetSchemaResponse.metadata:type_name -> cvt.SchemaMetadata
	3,  // 10: cvt.ListSchemasResponse.schemas:type_name -> cvt.SchemaMetadata
	10, // 11: cvt.CompareSchemasResponse.breaking_changes:type_name -> cvt.BreakingChange
	3,  // 12: cvt.CompareSchemasResponse.old_schema:type_name -> cvt.SchemaMetadata
	3,  // 13: cvt.CompareSchemasResponse.new_schema:type_name -> cvt.SchemaMetadata
	1,  // 14: cvt.GenerateFixtureRequest.output_type:type_name -> cvt.OutputType
	19, // 15: cvt.GenerateFixtureResponse.fixture:type_name -> cvt.GeneratedFixture
	21, // 16: cvt.GenerateFixtureResponse.response:type_name -> cvt.GeneratedResponse
	20, // 17: cvt.GeneratedFixture.request:type_name -> cvt.GeneratedRequest
	21, // 18: cvt.GeneratedFixture.response:type_name -> cvt.GeneratedResponse
	39, // 19: cvt.GeneratedRequest.headers:type_name -> cvt.GeneratedRequest.HeadersEntry
	40, // 20: cvt.GeneratedResponse.headers:type_name -> cvt.GeneratedResponse.HeadersEntry
	24, // 21: cvt.ListEndpointsResponse.endpoints:type_name -> cvt.EndpointInfo
	8,  // 22: cvt.ValidateProducerRequest.response:type_name -> cvt.ResponseData
	7,  // 23: cvt.ValidateProducerRequest.request:type_name -> cvt.RequestData
	27, // 24: cvt.ConsumerInfo.used_endpoints:type_name -> cvt.EndpointUsage
	27, // 25: cvt.RegisterConsumerRequest.used_endpoints:type_name -> cvt.EndpointUsage
	26, // 26: cvt.RegisterConsumerResponse.consumer:type_name -> cvt.ConsumerInfo
	26, // 27: cvt.ListConsumersResponse.consumers:type_name -> cvt.ConsumerInfo
	10, // 28: cvt.CanIDeployResponse.breaking_changes:type_name -> cvt.BreakingChange
	36, // 29: cvt.CanIDeployResponse.affected_consumers:type_name -> cvt.ConsumerImpact
	10, // 30: cvt.ConsumerImpact.relevant_changes:type_name -> cvt.BreakingChange
	4,  // 31: cvt.ContractValidator.RegisterSchema:input_type -> cvt.RegisterSchemaRequest
	6,  // 32: cvt.ContractValidator.ValidateInteraction:input_type -> cvt.InteractionRequest
	11, // 33: cvt.ContractValidator.GetSchema:input_type -> cvt.GetSchemaRequest
	13, // 34: cvt.ContractValidator.ListSchemas:input_type -> cvt.ListSchemasRequest
	15, // 35: cvt.ContractValidator.CompareSchemas:input_type -> cvt.CompareSchemasRequest
	17, // 36: cvt.ContractValidator.GenerateFixture:input_type -> cvt.GenerateFixtureRequest
	22, // 37: cvt.ContractValidator.ListEndpoints:input_type -> cvt.ListEndpointsRequest
	25, // 38: cvt.ContractValidator.ValidateProducerResponse:input_type -> cvt.ValidateProducerRequest
	28, // 39: cvt.ContractValidator.RegisterConsumer:input_type -> cvt.RegisterConsumerRequest
	30, // 40: cvt.ContractValidator.ListConsumers:input_type -> cvt.ListConsumersRequest
	32, // 41: cvt.ContractValidator.DeregisterConsumer:input_type -> cvt.DeregisterConsumerRequest
	34, // 42: cvt.ContractValidator.CanIDeploy:input_type -> cvt.CanIDeployRequest
	5,  // 43: cvt.ContractValidator.RegisterSchema:output_type -> cvt.RegisterSchemaResponse
	9,  // 44: cvt.ContractValidator.ValidateInteraction:output_type -> cvt.ValidationResult
	12, // 45: cvt.ContractValidator.GetSchema:output_type -> cvt.GetSchemaResponse
	14, // 46: cvt.ContractValidator.ListSchemas:output_type -> cvt.ListSchemasResponse
	16, // 47: cvt.ContractValidator.CompareSchemas:output_type -> cvt.CompareSchemasResponse
	18, // 48: cvt.ContractValidator.GenerateFixture:output_type -> cvt.GenerateFixtureResponse
	23, // 49: cvt.ContractValidator.ListEndpoints:output_type -> cvt.ListEndpointsResponse
	9,  // 50: cvt.ContractValidator.ValidateProducerResponse:output_type -> cvt.ValidationResult
	29, // 51: cvt.ContractValidator.RegisterConsumer:output_type -> cvt.RegisterConsumerResponse
	31, // 52: cvt.ContractValidator.ListConsumers:output_type -> cvt.ListConsumersResponse
	33, // 53: cvt.ContractValidator.DeregisterConsumer:output_type -> cvt.DeregisterConsumerResponse
	35, // 54: cvt.ContractValidator.CanIDeploy:output_type -> cvt.CanIDeployResponse
	43, // [43:55] is the sub-list for method output_type
	31, // [31:43] is the sub-list for method input_type
	31, // [31:31] is the sub-list for extension type_name
	31, // [31:31] is the sub-list for extension extendee
	0,  // [0:31] is the sub-list for field type_name
}

func init() { file_api_protos_cvt_proto_init() }
func file_api_protos_cvt_proto_init() {
	if File_api_protos_cvt_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_protos_cvt_proto_rawDesc), len(file_api_protos_cvt_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   39,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_protos_cvt_proto_goTypes,
		DependencyIndexes: file_api_protos_cvt_proto_depIdxs,
		EnumInfos:         file_api_protos_cvt_proto_enumTypes,
		MessageInfos:      file_api_protos_cvt_proto_msgTypes,
	}.Build()
	File_api_protos_cvt_proto = out.File
	file_api_protos_cvt_proto_goTypes = nil
	file_api_protos_cvt_proto_depIdxs = nil
}
