// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: api/protos/cvt.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ContractValidator_RegisterSchema_FullMethodName           = "/cvt.ContractValidator/RegisterSchema"
	ContractValidator_ValidateInteraction_FullMethodName      = "/cvt.ContractValidator/ValidateInteraction"
	ContractValidator_GetSchema_FullMethodName                = "/cvt.ContractValidator/GetSchema"
	ContractValidator_ListSchemas_FullMethodName              = "/cvt.ContractValidator/ListSchemas"
	ContractValidator_CompareSchemas_FullMethodName           = "/cvt.ContractValidator/CompareSchemas"
	ContractValidator_GenerateFixture_FullMethodName          = "/cvt.ContractValidator/GenerateFixture"
	ContractValidator_ListEndpoints_FullMethodName            = "/cvt.ContractValidator/ListEndpoints"
	ContractValidator_ValidateProducerResponse_FullMethodName = "/cvt.ContractValidator/ValidateProducerResponse"
	ContractValidator_RegisterConsumer_FullMethodName         = "/cvt.ContractValidator/RegisterConsumer"
	ContractValidator_ListConsumers_FullMethodName            = "/cvt.ContractValidator/ListConsumers"
	ContractValidator_DeregisterConsumer_FullMethodName       = "/cvt.ContractValidator/DeregisterConsumer"
	ContractValidator_CanIDeploy_FullMethodName               = "/cvt.ContractValidator/CanIDeploy"
)

// ContractValidatorClient is the client API for ContractValidator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ContractValidatorClient interface {
	// Registers an OpenAPI schema for future validation
	RegisterSchema(ctx context.Context, in *RegisterSchemaRequest, opts ...grpc.CallOption) (*RegisterSchemaResponse, error)
	// Validates a single request/response interaction against a registered schema
	ValidateInteraction(ctx context.Context, in *InteractionRequest, opts ...grpc.CallOption) (*ValidationResult, error)
	// Gets metadata for a registered schema
	GetSchema(ctx context.Context, in *GetSchemaRequest, opts ...grpc.CallOption) (*GetSchemaResponse, error)
	// Lists all registered schemas
	ListSchemas(ctx context.Context, in *ListSchemasRequest, opts ...grpc.CallOption) (*ListSchemasResponse, error)
	// Compares two schema versions for breaking changes
	CompareSchemas(ctx context.Context, in *CompareSchemasRequest, opts ...grpc.CallOption) (*CompareSchemasResponse, error)
	// Generates test fixtures from an OpenAPI schema
	GenerateFixture(ctx context.Context, in *GenerateFixtureRequest, opts ...grpc.CallOption) (*GenerateFixtureResponse, error)
	// Lists all endpoints available in a schema
	ListEndpoints(ctx context.Context, in *ListEndpointsRequest, opts ...grpc.CallOption) (*ListEndpointsResponse, error)
	// Validates a producer's response against its OpenAPI schema (for producer contract tests)
	ValidateProducerResponse(ctx context.Context, in *ValidateProducerRequest, opts ...grpc.CallOption) (*ValidationResult, error)
	// Registers a consumer's dependency on a schema
	RegisterConsumer(ctx context.Context, in *RegisterConsumerRequest, opts ...grpc.CallOption) (*RegisterConsumerResponse, error)
	// Lists all consumers that depend on a schema
	ListConsumers(ctx context.Context, in *ListConsumersRequest, opts ...grpc.CallOption) (*ListConsumersResponse, error)
	// Removes a consumer registration
	DeregisterConsumer(ctx context.Context, in *DeregisterConsumerRequest, opts ...grpc.CallOption) (*DeregisterConsumerResponse, error)
	// Checks if a schema version can be safely deployed
	CanIDeploy(ctx context.Context, in *CanIDeployRequest, opts ...grpc.CallOption) (*CanIDeployResponse, error)
}

type contractValidatorClient struct {
	cc grpc.ClientConnInterface
}

func NewContractValidatorClient(cc grpc.ClientConnInterface) ContractValidatorClient {
	return &contractValidatorClient{cc}
}

func (c *contractValidatorClient) RegisterSchema(ctx context.Context, in *RegisterSchemaRequest, opts ...grpc.CallOption) (*RegisterSchemaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterSchemaResponse)
	err := c.cc.Invoke(ctx, ContractValidator_RegisterSchema_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contractValidatorClient) ValidateInteraction(ctx context.Context, in *InteractionRequest, opts ...grpc.CallOption) (*ValidationResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidationResult)
	err := c.cc.Invoke(ctx, ContractValidator_ValidateInteraction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contractValidatorClient) GetSchema(ctx context.Context, in *GetSchemaRequest, opts ...grpc.CallOption) (*GetSchemaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSchemaResponse)
	err := c.cc.Invoke(ctx, ContractValidator_GetSchema_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contractValidatorClient) ListSchemas(ctx context.Context, in *ListSchemasRequest, opts ...grpc.CallOption) (*ListSchemasResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSchemasResponse)
	err := c.cc.Invoke(ctx, ContractValidator_ListSchemas_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contractValidatorClient) CompareSchemas(ctx context.Context, in *CompareSchemasRequest, opts ...grpc.CallOption) (*CompareSchemasResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompareSchemasResponse)
	err := c.cc.Invoke(ctx, ContractValidator_CompareSchemas_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contractValidatorClient) GenerateFixture(ctx context.Context, in *GenerateFixtureRequest, opts ...grpc.CallOption) (*GenerateFixtureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateFixtureResponse)
	err := c.cc.Invoke(ctx, ContractValidator_GenerateFixture_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contractValidatorClient) ListEndpoints(ctx context.Context, in *ListEndpointsRequest, opts ...grpc.CallOption) (*ListEndpointsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListEndpointsResponse)
	err := c.cc.Invoke(ctx, ContractValidator_ListEndpoints_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contractValidatorClient) ValidateProducerResponse(ctx context.Context, in *ValidateProducerRequest, opts ...grpc.CallOption) (*ValidationResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidationResult)
	err := c.cc.Invoke(ctx, ContractValidator_ValidateProducerResponse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contractValidatorClient) RegisterConsumer(ctx context.Context, in *RegisterConsumerRequest, opts ...grpc.CallOption) (*RegisterConsumerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterConsumerResponse)
	err := c.cc.Invoke(ctx, ContractValidator_RegisterConsumer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contractValidatorClient) ListConsumers(ctx context.Context, in *ListConsumersRequest, opts ...grpc.CallOption) (*ListConsumersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListConsumersResponse)
	err := c.cc.Invoke(ctx, ContractValidator_ListConsumers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contractValidatorClient) DeregisterConsumer(ctx context.Context, in *DeregisterConsumerRequest, opts ...grpc.CallOption) (*DeregisterConsumerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeregisterConsumerResponse)
	err := c.cc.Invoke(ctx, ContractValidator_DeregisterConsumer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contractValidatorClient) CanIDeploy(ctx context.Context, in *CanIDeployRequest, opts ...grpc.CallOption) (*CanIDeployResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CanIDeployResponse)
	err := c.cc.Invoke(ctx, ContractValidator_CanIDeploy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContractValidatorServer is the server API for ContractValidator service.
// All implementations must embed UnimplementedContractValidatorServer
// for forward compatibility.
type ContractValidatorServer interface {
	// Registers an OpenAPI schema for future validation
	RegisterSchema(context.Context, *RegisterSchemaRequest) (*RegisterSchemaResponse, error)
	// Validates a single request/response interaction against a registered schema
	ValidateInteraction(context.Context, *InteractionRequest) (*ValidationResult, error)
	// Gets metadata for a registered schema
	GetSchema(context.Context, *GetSchemaRequest) (*GetSchemaResponse, error)
	// Lists all registered schemas
	ListSchemas(context.Context, *ListSchemasRequest) (*ListSchemasResponse, error)
	// Compares two schema versions for breaking changes
	CompareSchemas(context.Context, *CompareSchemasRequest) (*CompareSchemasResponse, error)
	// Generates test fixtures from an OpenAPI schema
	GenerateFixture(context.Context, *GenerateFixtureRequest) (*GenerateFixtureResponse, error)
	// Lists all endpoints available in a schema
	ListEndpoints(context.Context, *ListEndpointsRequest) (*ListEndpointsResponse, error)
	// Validates a producer's response against its OpenAPI schema (for producer contract tests)
	ValidateProducerResponse(context.Context, *ValidateProducerRequest) (*ValidationResult, error)
	// Registers a consumer's dependency on a schema
	RegisterConsumer(context.Context, *RegisterConsumerRequest) (*RegisterConsumerResponse, error)
	// Lists all consumers that depend on a schema
	ListConsumers(context.Context, *ListConsumersRequest) (*ListConsumersResponse, error)
	// Removes a consumer registration
	DeregisterConsumer(context.Context, *DeregisterConsumerRequest) (*DeregisterConsumerResponse, error)
	// Checks if a schema version can be safely deployed
	CanIDeploy(context.Context, *CanIDeployRequest) (*CanIDeployResponse, error)
	mustEmbedUnimplementedContractValidatorServer()
}

// UnimplementedContractValidatorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedContractValidatorServer struct{}

func (UnimplementedContractValidatorServer) RegisterSchema(context.Context, *RegisterSchemaRequest) (*RegisterSchemaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterSchema not implemented")
}
func (UnimplementedContractValidatorServer) ValidateInteraction(context.Context, *InteractionRequest) (*ValidationResult, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateInteraction not implemented")
}
func (UnimplementedContractValidatorServer) GetSchema(context.Context, *GetSchemaRequest) (*GetSchemaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSchema not implemented")
}
func (UnimplementedContractValidatorServer) ListSchemas(context.Context, *ListSchemasRequest) (*ListSchemasResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSchemas not implemented")
}
func (UnimplementedContractValidatorServer) CompareSchemas(context.Context, *CompareSchemasRequest) (*CompareSchemasResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompareSchemas not implemented")
}
func (UnimplementedContractValidatorServer) GenerateFixture(context.Context, *GenerateFixtureRequest) (*GenerateFixtureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateFixture not implemented")
}
func (UnimplementedContractValidatorServer) ListEndpoints(context.Context, *ListEndpointsRequest) (*ListEndpointsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListEndpoints not implemented")
}
func (UnimplementedContractValidatorServer) ValidateProducerResponse(context.Context, *ValidateProducerRequest) (*ValidationResult, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateProducerResponse not implemented")
}
func (UnimplementedContractValidatorServer) RegisterConsumer(context.Context, *RegisterConsumerRequest) (*RegisterConsumerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterConsumer not implemented")
}
func (UnimplementedContractValidatorServer) ListConsumers(context.Context, *ListConsumersRequest) (*ListConsumersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListConsumers not implemented")
}
func (UnimplementedContractValidatorServer) DeregisterConsumer(context.Context, *DeregisterConsumerRequest) (*DeregisterConsumerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeregisterConsumer not implemented")
}
func (UnimplementedContractValidatorServer) CanIDeploy(context.Context, *CanIDeployRequest) (*CanIDeployResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CanIDeploy not implemented")
}
func (UnimplementedContractValidatorServer) mustEmbedUnimplementedContractValidatorServer() {}
func (UnimplementedContractValidatorServer) testEmbeddedByValue()                           {}

// UnsafeContractValidatorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ContractValidatorServer will
// result in compilation errors.
type UnsafeContractValidatorServer interface {
	mustEmbedUnimplementedContractValidatorServer()
}

func RegisterContractValidatorServer(s grpc.ServiceRegistrar, srv ContractValidatorServer) {
	// If the following call panics, it indicates UnimplementedContractValidatorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ContractValidator_ServiceDesc, srv)
}

func _ContractValidator_RegisterSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContractValidatorServer).RegisterSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContractValidator_RegisterSchema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContractValidatorServer).RegisterSchema(ctx, req.(*RegisterSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContractValidator_ValidateInteraction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InteractionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContractValidatorServer).ValidateInteraction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContractValidator_ValidateInteraction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContractValidatorServer).ValidateInteraction(ctx, req.(*InteractionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContractValidator_GetSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContractValidatorServer).GetSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContractValidator_GetSchema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContractValidatorServer).GetSchema(ctx, req.(*GetSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContractValidator_ListSchemas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSchemasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContractValidatorServer).ListSchemas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContractValidator_ListSchemas_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContractValidatorServer).ListSchemas(ctx, req.(*ListSchemasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContractValidator_CompareSchemas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompareSchemasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContractValidatorServer).CompareSchemas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContractValidator_CompareSchemas_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContractValidatorServer).CompareSchemas(ctx, req.(*CompareSchemasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContractValidator_GenerateFixture_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateFixtureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContractValidatorServer).GenerateFixture(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContractValidator_GenerateFixture_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContractValidatorServer).GenerateFixture(ctx, req.(*GenerateFixtureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContractValidator_ListEndpoints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEndpointsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContractValidatorServer).ListEndpoints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContractValidator_ListEndpoints_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContractValidatorServer).ListEndpoints(ctx, req.(*ListEndpointsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContractValidator_ValidateProducerResponse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateProducerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContractValidatorServer).ValidateProducerResponse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContractValidator_ValidateProducerResponse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContractValidatorServer).ValidateProducerResponse(ctx, req.(*ValidateProducerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContractValidator_RegisterConsumer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterConsumerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContractValidatorServer).RegisterConsumer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContractValidator_RegisterConsumer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContractValidatorServer).RegisterConsumer(ctx, req.(*RegisterConsumerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContractValidator_ListConsumers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListConsumersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContractValidatorServer).ListConsumers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContractValidator_ListConsumers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContractValidatorServer).ListConsumers(ctx, req.(*ListConsumersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContractValidator_DeregisterConsumer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeregisterConsumerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContractValidatorServer).DeregisterConsumer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContractValidator_DeregisterConsumer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContractValidatorServer).DeregisterConsumer(ctx, req.(*DeregisterConsumerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContractValidator_CanIDeploy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CanIDeployRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContractValidatorServer).CanIDeploy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContractValidator_CanIDeploy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContractValidatorServer).CanIDeploy(ctx, req.(*CanIDeployRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ContractValidator_ServiceDesc is the grpc.ServiceDesc for ContractValidator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ContractValidator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cvt.ContractValidator",
	HandlerType: (*ContractValidatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterSchema",
			Handler:    _ContractValidator_RegisterSchema_Handler,
		},
		{
			MethodName: "ValidateInteraction",
			Handler:    _ContractValidator_ValidateInteraction_Handler,
		},
		{
			MethodName: "GetSchema",
			Handler:    _ContractValidator_GetSchema_Handler,
		},
		{
			MethodName: "ListSchemas",
			Handler:    _ContractValidator_ListSchemas_Handler,
		},
		{
			MethodName: "CompareSchemas",
			Handler:    _ContractValidator_CompareSchemas_Handler,
		},
		{
			MethodName: "GenerateFixture",
			Handler:    _ContractValidator_GenerateFixture_Handler,
		},
		{
			MethodName: "ListEndpoints",
			Handler:    _ContractValidator_ListEndpoints_Handler,
		},
		{
			MethodName: "ValidateProducerResponse",
			Handler:    _ContractValidator_ValidateProducerResponse_Handler,
		},
		{
			MethodName: "RegisterConsumer",
			Handler:    _ContractValidator_RegisterConsumer_Handler,
		},
		{
			MethodName: "ListConsumers",
			Handler:    _ContractValidator_ListConsumers_Handler,
		},
		{
			MethodName: "DeregisterConsumer",
			Handler:    _ContractValidator_DeregisterConsumer_Handler,
		},
		{
			MethodName: "CanIDeploy",
			Handler:    _ContractValidator_CanIDeploy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/protos/cvt.proto",
}
