// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v7.34.1
// source: api/protos/plugin/events/v1/events.proto

package eventspb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// EventHandlerClient is the client API for EventHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EventHandlerClient interface {
	OnBreakingChangeDetected(ctx context.Context, in *BreakingChangeDetectedRequest, opts ...grpc.CallOption) (*EventResponse, error)
	OnValidationFailed(ctx context.Context, in *ValidationFailedRequest, opts ...grpc.CallOption) (*EventResponse, error)
}

type eventHandlerClient struct {
	cc grpc.ClientConnInterface
}

func NewEventHandlerClient(cc grpc.ClientConnInterface) EventHandlerClient {
	return &eventHandlerClient{cc}
}

func (c *eventHandlerClient) OnBreakingChangeDetected(ctx context.Context, in *BreakingChangeDetectedRequest, opts ...grpc.CallOption) (*EventResponse, error) {
	out := new(EventResponse)
	err := c.cc.Invoke(ctx, "/cvt.plugin.events.v1.EventHandler/OnBreakingChangeDetected", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventHandlerClient) OnValidationFailed(ctx context.Context, in *ValidationFailedRequest, opts ...grpc.CallOption) (*EventResponse, error) {
	out := new(EventResponse)
	err := c.cc.Invoke(ctx, "/cvt.plugin.events.v1.EventHandler/OnValidationFailed", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventHandlerServer is the server API for EventHandler service.
// All implementations must embed UnimplementedEventHandlerServer
// for forward compatibility
type EventHandlerServer interface {
	OnBreakingChangeDetected(context.Context, *BreakingChangeDetectedRequest) (*EventResponse, error)
	OnValidationFailed(context.Context, *ValidationFailedRequest) (*EventResponse, error)
	mustEmbedUnimplementedEventHandlerServer()
}

// UnimplementedEventHandlerServer must be embedded to have forward compatible implementations.
type UnimplementedEventHandlerServer struct {
}

func (UnimplementedEventHandlerServer) OnBreakingChangeDetected(context.Context, *BreakingChangeDetectedRequest) (*EventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnBreakingChangeDetected not implemented")
}
func (UnimplementedEventHandlerServer) OnValidationFailed(context.Context, *ValidationFailedRequest) (*EventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnValidationFailed not implemented")
}
func (UnimplementedEventHandlerServer) mustEmbedUnimplementedEventHandlerServer() {}

// UnsafeEventHandlerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventHandlerServer will
// result in compilation errors.
type UnsafeEventHandlerServer interface {
	mustEmbedUnimplementedEventHandlerServer()
}

func RegisterEventHandlerServer(s grpc.ServiceRegistrar, srv EventHandlerServer) {
	s.RegisterService(&EventHandler_ServiceDesc, srv)
}

func _EventHandler_OnBreakingChangeDetected_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BreakingChangeDetectedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventHandlerServer).OnBreakingChangeDetected(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cvt.plugin.events.v1.EventHandler/OnBreakingChangeDetected",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventHandlerServer).OnBreakingChangeDetected(ctx, req.(*BreakingChangeDetectedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventHandler_OnValidationFailed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidationFailedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventHandlerServer).OnValidationFailed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cvt.plugin.events.v1.EventHandler/OnValidationFailed",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventHandlerServer).OnValidationFailed(ctx, req.(*ValidationFailedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EventHandler_ServiceDesc is the grpc.ServiceDesc for EventHandler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EventHandler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cvt.plugin.events.v1.EventHandler",
	HandlerType: (*EventHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OnBreakingChangeDetected",
			Handler:    _EventHandler_OnBreakingChangeDetected_Handler,
		},
		{
			MethodName: "OnValidationFailed",
			Handler:    _EventHandler_OnValidationFailed_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/protos/plugin/events/v1/events.proto",
}
