// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/protos/plugin/events/v1/events.proto

package eventspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BreakingChangeDetectedRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	RequestId  string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	SchemaId   string                 `protobuf:"bytes,2,opt,name=schema_id,json=schemaId,proto3" json:"schema_id,omitempty"`
	OldVersion string                 `protobuf:"bytes,3,opt,name=old_version,json=oldVersion,proto3" json:"old_version,omitempty"`
	NewVersion string                 `protobuf:"bytes,4,opt,name=new_version,json=newVersion,proto3" json:"new_version,omitempty"`
	Changes    []*BreakingChange      `protobuf:"bytes,5,rep,name=changes,proto3" json:"changes,omitempty"`
	// Where the detection happened. One of: "CompareSchemas", "RegisterSchema".
	DetectedBy    string `protobuf:"bytes,6,opt,name=detected_by,json=detectedBy,proto3" json:"detected_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BreakingChangeDetectedRequest) Reset() {
	*x = BreakingChangeDetectedRequest{}
	mi := &file_api_protos_plugin_events_v1_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BreakingChangeDetectedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BreakingChangeDetectedRequest) ProtoMessage() {}

func (x *BreakingChangeDetectedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_plugin_events_v1_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BreakingChangeDetectedRequest.ProtoReflect.Descriptor instead.
func (*BreakingChangeDetectedRequest) Descriptor() ([]byte, []int) {
	return file_api_protos_plugin_events_v1_events_proto_rawDescGZIP(), []int{0}
}

func (x *BreakingChangeDetectedRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *BreakingChangeDetectedRequest) GetSchemaId() string {
	if x != nil {
		return x.SchemaId
	}
	return ""
}

func (x *BreakingChangeDetectedRequest) GetOldVersion() string {
	if x != nil {
		return x.OldVersion
	}
	return ""
}

func (x *BreakingChangeDetectedRequest) GetNewVersion() string {
	if x != nil {
		return x.NewVersion
	}
	return ""
}

func (x *BreakingChangeDetectedRequest) GetChanges() []*BreakingChange {
	if x != nil {
		return x.Changes
	}
	return nil
}

func (x *BreakingChangeDetectedRequest) GetDetectedBy() string {
	if x != nil {
		return x.DetectedBy
	}
	return ""
}

type BreakingChange struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Machine-readable category. Examples: "removed_endpoint",
	// "required_field_added", "response_type_narrowed".
	Kind string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	// Human-readable description.
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// The endpoint involved, when applicable.
	Method string `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	Path   string `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	// Structured field path when available, e.g., "responses.200.schema.properties.id".
	FieldPath     string `protobuf:"bytes,5,opt,name=field_path,json=fieldPath,proto3" json:"field_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BreakingChange) Reset() {
	*x = BreakingChange{}
	mi := &file_api_protos_plugin_events_v1_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BreakingChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BreakingChange) ProtoMessage() {}

func (x *BreakingChange) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_plugin_events_v1_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BreakingChange.ProtoReflect.Descriptor instead.
func (*BreakingChange) Descriptor() ([]byte, []int) {
	return file_api_protos_plugin_events_v1_events_proto_rawDescGZIP(), []int{1}
}

func (x *BreakingChange) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *BreakingChange) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *BreakingChange) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *BreakingChange) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *BreakingChange) GetFieldPath() string {
	if x != nil {
		return x.FieldPath
	}
	return ""
}

type ValidationFailedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	SchemaId      string                 `protobuf:"bytes,2,opt,name=schema_id,json=schemaId,proto3" json:"schema_id,omitempty"`
	Method        string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	Errors        []*ValidationError     `protobuf:"bytes,5,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidationFailedRequest) Reset() {
	*x = ValidationFailedRequest{}
	mi := &file_api_protos_plugin_events_v1_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationFailedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationFailedRequest) ProtoMessage() {}

func (x *ValidationFailedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_plugin_events_v1_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationFailedRequest.ProtoReflect.Descriptor instead.
func (*ValidationFailedRequest) Descriptor() ([]byte, []int) {
	return file_api_protos_plugin_events_v1_events_proto_rawDescGZIP(), []int{2}
}

func (x *ValidationFailedRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ValidationFailedRequest) GetSchemaId() string {
	if x != nil {
		return x.SchemaId
	}
	return ""
}

func (x *ValidationFailedRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *ValidationFailedRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ValidationFailedRequest) GetErrors() []*ValidationError {
	if x != nil {
		return x.Errors
	}
	return nil
}

type ValidationError struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Machine-readable category, e.g., "request.body.missing_field",
	// "response.status_code.unexpected".
	Kind string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	// Human-readable description.
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// Structured field path when available.
	FieldPath     string `protobuf:"bytes,3,opt,name=field_path,json=fieldPath,proto3" json:"field_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidationError) Reset() {
	*x = ValidationError{}
	mi := &file_api_protos_plugin_events_v1_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationError) ProtoMessage() {}

func (x *ValidationError) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_plugin_events_v1_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationError.ProtoReflect.Descriptor instead.
func (*ValidationError) Descriptor() ([]byte, []int) {
	return file_api_protos_plugin_events_v1_events_proto_rawDescGZIP(), []int{3}
}

func (x *ValidationError) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ValidationError) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ValidationError) GetFieldPath() string {
	if x != nil {
		return x.FieldPath
	}
	return ""
}

type EventResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Plugin acknowledges receipt. Core treats ack=false the same as ack=true;
	// this field exists for plugin authors who want to signal a soft problem
	// without returning a gRPC error.
	Acknowledged  bool `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventResponse) Reset() {
	*x = EventResponse{}
	mi := &file_api_protos_plugin_events_v1_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventResponse) ProtoMessage() {}

func (x *EventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_plugin_events_v1_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventResponse.ProtoReflect.Descriptor instead.
func (*EventResponse) Descriptor() ([]byte, []int) {
	return file_api_protos_plugin_events_v1_events_proto_rawDescGZIP(), []int{4}
}

func (x *EventResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

var File_api_protos_plugin_events_v1_events_proto protoreflect.FileDescriptor

const file_api_protos_plugin_events_v1_events_proto_rawDesc = "" +
	"\n" +
	"(api/protos/plugin/events/v1/events.proto\x12\x14cvt.plugin.events.v1\"\xfe\x01\n" +
	"\x1dBreakingChangeDetectedRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1b\n" +
	"\tschema_id\x18\x02 \x01(\tR\bschemaId\x12\x1f\n" +
	"\vold_version\x18\x03 \x01(\tR\n" +
	"oldVersion\x12\x1f\n" +
	"\vnew_version\x18\x04 \x01(\tR\n" +
	"newVersion\x12>\n" +
	"\achanges\x18\x05 \x03(\v2$.cvt.plugin.events.v1.BreakingChangeR\achanges\x12\x1f\n" +
	"\vdetected_by\x18\x06 \x01(\tR\n" +
	"detectedBy\"\x91\x01\n" +
	"\x0eBreakingChange\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12\x1d\n" +
	"\n" +
	"field_path\x18\x05 \x01(\tR\tfieldPath\"\xc0\x01\n" +
	"\x17ValidationFailedRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1b\n" +
	"\tschema_id\x18\x02 \x01(\tR\bschemaId\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12=\n" +
	"\x06errors\x18\x05 \x03(\v2%.cvt.plugin.events.v1.ValidationErrorR\x06errors\"f\n" +
	"\x0fValidationError\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"field_path\x18\x03 \x01(\tR\tfieldPath\"3\n" +
	"\rEventResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged2\xee\x01\n" +
	"\fEventHandler\x12t\n" +
	"\x18OnBreakingChangeDetected\x123.cvt.plugin.events.v1.BreakingChangeDetectedRequest\x1a#.cvt.plugin.events.v1.EventResponse\x12h\n" +
	"\x12OnValidationFailed\x12-.cvt.plugin.events.v1.ValidationFailedRequest\x1a#.cvt.plugin.events.v1.EventResponseB;Z9github.com/sahina/cvt/pkg/cvtplugin/pb/events/v1;eventspbb\x06proto3"

var (
	file_api_protos_plugin_events_v1_events_proto_rawDescOnce sync.Once
	file_api_protos_plugin_events_v1_events_proto_rawDescData []byte
)

func file_api_protos_plugin_events_v1_events_proto_rawDescGZIP() []byte {
	file_api_protos_plugin_events_v1_events_proto_rawDescOnce.Do(func() {
		file_api_protos_plugin_events_v1_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_protos_plugin_events_v1_events_proto_rawDesc), len(file_api_protos_plugin_events_v1_events_proto_rawDesc)))
	})
	return file_api_protos_plugin_events_v1_events_proto_rawDescData
}

var file_api_protos_plugin_events_v1_events_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_protos_plugin_events_v1_events_proto_goTypes = []any{
	(*BreakingChangeDetectedRequest)(nil), // 0: cvt.plugin.events.v1.BreakingChangeDetectedRequest
	(*BreakingChange)(nil),                // 1: cvt.plugin.events.v1.BreakingChange
	(*ValidationFailedRequest)(nil),       // 2: cvt.plugin.events.v1.ValidationFailedRequest
	(*ValidationError)(nil),               // 3: cvt.plugin.events.v1.ValidationError
	(*EventResponse)(nil),                 // 4: cvt.plugin.events.v1.EventResponse
}
var file_api_protos_plugin_events_v1_events_proto_depIdxs = []int32{
	1, // 0: cvt.plugin.events.v1.BreakingChangeDetectedRequest.changes:type_name -> cvt.plugin.events.v1.BreakingChange
	3, // 1: cvt.plugin.events.v1.ValidationFailedRequest.errors:type_name -> cvt.plugin.events.v1.ValidationError
	0, // 2: cvt.plugin.events.v1.EventHandler.OnBreakingChangeDetected:input_type -> cvt.plugin.events.v1.BreakingChangeDetectedRequest
	2, // 3: cvt.plugin.events.v1.EventHandler.OnValidationFailed:input_type -> cvt.plugin.events.v1.ValidationFailedRequest
	4, // 4: cvt.plugin.events.v1.EventHandler.OnBreakingChangeDetected:output_type -> cvt.plugin.events.v1.EventResponse
	4, // 5: cvt.plugin.events.v1.EventHandler.OnValidationFailed:output_type -> cvt.plugin.events.v1.EventResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_protos_plugin_events_v1_events_proto_init() }
func file_api_protos_plugin_events_v1_events_proto_init() {
	if File_api_protos_plugin_events_v1_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_protos_plugin_events_v1_events_proto_rawDesc), len(file_api_protos_plugin_events_v1_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_protos_plugin_events_v1_events_proto_goTypes,
		DependencyIndexes: file_api_protos_plugin_events_v1_events_proto_depIdxs,
		MessageInfos:      file_api_protos_plugin_events_v1_events_proto_msgTypes,
	}.Build()
	File_api_protos_plugin_events_v1_events_proto = out.File
	file_api_protos_plugin_events_v1_events_proto_goTypes = nil
	file_api_protos_plugin_events_v1_events_proto_depIdxs = nil
}
