// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v7.34.1
// source: api/protos/plugin/registry/v1/registry.proto

package registrypb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RegistryProviderClient is the client API for RegistryProvider service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RegistryProviderClient interface {
	// FetchSchema retrieves an OpenAPI spec from the registry. schema_id maps
	// to info.title in the spec. version maps to info.version; empty string
	// means "latest" and the registry chooses.
	//
	// Read semantics: MAY be called concurrently. Should be idempotent. Plugins
	// that cache the registry response should honor a short TTL or the caller's
	// explicit invalidation.
	FetchSchema(ctx context.Context, in *FetchSchemaRequest, opts ...grpc.CallOption) (*FetchSchemaResponse, error)
	// RegisterConsumerUsage records that a consumer validated its interactions
	// against a specific schema + version. Typically called once per successful
	// `cvt validate` invocation.
	//
	// Write semantics: MUST be idempotent upsert. Core guarantees at-most-one
	// plugin per hook in v1, but the plugin's own deduplication protects against
	// retries and replays.
	RegisterConsumerUsage(ctx context.Context, in *RegisterConsumerUsageRequest, opts ...grpc.CallOption) (*RegisterConsumerUsageResponse, error)
}

type registryProviderClient struct {
	cc grpc.ClientConnInterface
}

func NewRegistryProviderClient(cc grpc.ClientConnInterface) RegistryProviderClient {
	return &registryProviderClient{cc}
}

func (c *registryProviderClient) FetchSchema(ctx context.Context, in *FetchSchemaRequest, opts ...grpc.CallOption) (*FetchSchemaResponse, error) {
	out := new(FetchSchemaResponse)
	err := c.cc.Invoke(ctx, "/cvt.plugin.registry.v1.RegistryProvider/FetchSchema", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryProviderClient) RegisterConsumerUsage(ctx context.Context, in *RegisterConsumerUsageRequest, opts ...grpc.CallOption) (*RegisterConsumerUsageResponse, error) {
	out := new(RegisterConsumerUsageResponse)
	err := c.cc.Invoke(ctx, "/cvt.plugin.registry.v1.RegistryProvider/RegisterConsumerUsage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RegistryProviderServer is the server API for RegistryProvider service.
// All implementations must embed UnimplementedRegistryProviderServer
// for forward compatibility
type RegistryProviderServer interface {
	// FetchSchema retrieves an OpenAPI spec from the registry. schema_id maps
	// to info.title in the spec. version maps to info.version; empty string
	// means "latest" and the registry chooses.
	//
	// Read semantics: MAY be called concurrently. Should be idempotent. Plugins
	// that cache the registry response should honor a short TTL or the caller's
	// explicit invalidation.
	FetchSchema(context.Context, *FetchSchemaRequest) (*FetchSchemaResponse, error)
	// RegisterConsumerUsage records that a consumer validated its interactions
	// against a specific schema + version. Typically called once per successful
	// `cvt validate` invocation.
	//
	// Write semantics: MUST be idempotent upsert. Core guarantees at-most-one
	// plugin per hook in v1, but the plugin's own deduplication protects against
	// retries and replays.
	RegisterConsumerUsage(context.Context, *RegisterConsumerUsageRequest) (*RegisterConsumerUsageResponse, error)
	mustEmbedUnimplementedRegistryProviderServer()
}

// UnimplementedRegistryProviderServer must be embedded to have forward compatible implementations.
type UnimplementedRegistryProviderServer struct {
}

func (UnimplementedRegistryProviderServer) FetchSchema(context.Context, *FetchSchemaRequest) (*FetchSchemaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchSchema not implemented")
}
func (UnimplementedRegistryProviderServer) RegisterConsumerUsage(context.Context, *RegisterConsumerUsageRequest) (*RegisterConsumerUsageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterConsumerUsage not implemented")
}
func (UnimplementedRegistryProviderServer) mustEmbedUnimplementedRegistryProviderServer() {}

// UnsafeRegistryProviderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RegistryProviderServer will
// result in compilation errors.
type UnsafeRegistryProviderServer interface {
	mustEmbedUnimplementedRegistryProviderServer()
}

func RegisterRegistryProviderServer(s grpc.ServiceRegistrar, srv RegistryProviderServer) {
	s.RegisterService(&RegistryProvider_ServiceDesc, srv)
}

func _RegistryProvider_FetchSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryProviderServer).FetchSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cvt.plugin.registry.v1.RegistryProvider/FetchSchema",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryProviderServer).FetchSchema(ctx, req.(*FetchSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegistryProvider_RegisterConsumerUsage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterConsumerUsageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryProviderServer).RegisterConsumerUsage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cvt.plugin.registry.v1.RegistryProvider/RegisterConsumerUsage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryProviderServer).RegisterConsumerUsage(ctx, req.(*RegisterConsumerUsageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RegistryProvider_ServiceDesc is the grpc.ServiceDesc for RegistryProvider service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RegistryProvider_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cvt.plugin.registry.v1.RegistryProvider",
	HandlerType: (*RegistryProviderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FetchSchema",
			Handler:    _RegistryProvider_FetchSchema_Handler,
		},
		{
			MethodName: "RegisterConsumerUsage",
			Handler:    _RegistryProvider_RegisterConsumerUsage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/protos/plugin/registry/v1/registry.proto",
}
