// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/protos/plugin/registry/v1/registry.proto

package registrypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FetchSchemaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaId      string                 `protobuf:"bytes,1,opt,name=schema_id,json=schemaId,proto3" json:"schema_id,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`                      // empty = latest
	RequestId     string                 `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // correlation ID for logs/audit
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchSchemaRequest) Reset() {
	*x = FetchSchemaRequest{}
	mi := &file_api_protos_plugin_registry_v1_registry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchSchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchSchemaRequest) ProtoMessage() {}

func (x *FetchSchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_plugin_registry_v1_registry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchSchemaRequest.ProtoReflect.Descriptor instead.
func (*FetchSchemaRequest) Descriptor() ([]byte, []int) {
	return file_api_protos_plugin_registry_v1_registry_proto_rawDescGZIP(), []int{0}
}

func (x *FetchSchemaRequest) GetSchemaId() string {
	if x != nil {
		return x.SchemaId
	}
	return ""
}

func (x *FetchSchemaRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *FetchSchemaRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type FetchSchemaResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Spec            []byte                 `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`                                              // raw OpenAPI spec bytes (JSON or YAML)
	ResolvedVersion string                 `protobuf:"bytes,2,opt,name=resolved_version,json=resolvedVersion,proto3" json:"resolved_version,omitempty"` // actual version returned (useful when request was "latest")
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FetchSchemaResponse) Reset() {
	*x = FetchSchemaResponse{}
	mi := &file_api_protos_plugin_registry_v1_registry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchSchemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchSchemaResponse) ProtoMessage() {}

func (x *FetchSchemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_plugin_registry_v1_registry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchSchemaResponse.ProtoReflect.Descriptor instead.
func (*FetchSchemaResponse) Descriptor() ([]byte, []int) {
	return file_api_protos_plugin_registry_v1_registry_proto_rawDescGZIP(), []int{1}
}

func (x *FetchSchemaResponse) GetSpec() []byte {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *FetchSchemaResponse) GetResolvedVersion() string {
	if x != nil {
		return x.ResolvedVersion
	}
	return ""
}

type RegisterConsumerUsageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConsumerId    string                 `protobuf:"bytes,1,opt,name=consumer_id,json=consumerId,proto3" json:"consumer_id,omitempty"`
	SchemaId      string                 `protobuf:"bytes,2,opt,name=schema_id,json=schemaId,proto3" json:"schema_id,omitempty"`
	SchemaVersion string                 `protobuf:"bytes,3,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	Environment   string                 `protobuf:"bytes,4,opt,name=environment,proto3" json:"environment,omitempty"` // e.g., "ci", "staging", "production"
	Endpoints     []*EndpointUsage       `protobuf:"bytes,5,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	RequestId     string                 `protobuf:"bytes,6,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterConsumerUsageRequest) Reset() {
	*x = RegisterConsumerUsageRequest{}
	mi := &file_api_protos_plugin_registry_v1_registry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterConsumerUsageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterConsumerUsageRequest) ProtoMessage() {}

func (x *RegisterConsumerUsageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_plugin_registry_v1_registry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterConsumerUsageRequest.ProtoReflect.Descriptor instead.
func (*RegisterConsumerUsageRequest) Descriptor() ([]byte, []int) {
	return file_api_protos_plugin_registry_v1_registry_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterConsumerUsageRequest) GetConsumerId() string {
	if x != nil {
		return x.ConsumerId
	}
	return ""
}

func (x *RegisterConsumerUsageRequest) GetSchemaId() string {
	if x != nil {
		return x.SchemaId
	}
	return ""
}

func (x *RegisterConsumerUsageRequest) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *RegisterConsumerUsageRequest) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *RegisterConsumerUsageRequest) GetEndpoints() []*EndpointUsage {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *RegisterConsumerUsageRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type EndpointUsage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"` // e.g., "GET"
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`     // e.g., "/pets/{id}"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndpointUsage) Reset() {
	*x = EndpointUsage{}
	mi := &file_api_protos_plugin_registry_v1_registry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndpointUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointUsage) ProtoMessage() {}

func (x *EndpointUsage) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_plugin_registry_v1_registry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointUsage.ProtoReflect.Descriptor instead.
func (*EndpointUsage) Descriptor() ([]byte, []int) {
	return file_api_protos_plugin_registry_v1_registry_proto_rawDescGZIP(), []int{3}
}

func (x *EndpointUsage) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *EndpointUsage) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type RegisterConsumerUsageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterConsumerUsageResponse) Reset() {
	*x = RegisterConsumerUsageResponse{}
	mi := &file_api_protos_plugin_registry_v1_registry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterConsumerUsageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterConsumerUsageResponse) ProtoMessage() {}

func (x *RegisterConsumerUsageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_plugin_registry_v1_registry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterConsumerUsageResponse.ProtoReflect.Descriptor instead.
func (*RegisterConsumerUsageResponse) Descriptor() ([]byte, []int) {
	return file_api_protos_plugin_registry_v1_registry_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterConsumerUsageResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

var File_api_protos_plugin_registry_v1_registry_proto protoreflect.FileDescriptor

const file_api_protos_plugin_registry_v1_registry_proto_rawDesc = "" +
	"\n" +
	",api/protos/plugin/registry/v1/registry.proto\x12\x16cvt.plugin.registry.v1\"j\n" +
	"\x12FetchSchemaRequest\x12\x1b\n" +
	"\tschema_id\x18\x01 \x01(\tR\bschemaId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\"T\n" +
	"\x13FetchSchemaResponse\x12\x12\n" +
	"\x04spec\x18\x01 \x01(\fR\x04spec\x12)\n" +
	"\x10resolved_version\x18\x02 \x01(\tR\x0fresolvedVersion\"\x89\x02\n" +
	"\x1cRegisterConsumerUsageRequest\x12\x1f\n" +
	"\vconsumer_id\x18\x01 \x01(\tR\n" +
	"consumerId\x12\x1b\n" +
	"\tschema_id\x18\x02 \x01(\tR\bschemaId\x12%\n" +
	"\x0eschema_version\x18\x03 \x01(\tR\rschemaVersion\x12 \n" +
	"\venvironment\x18\x04 \x01(\tR\venvironment\x12C\n" +
	"\tendpoints\x18\x05 \x03(\v2%.cvt.plugin.registry.v1.EndpointUsageR\tendpoints\x12\x1d\n" +
	"\n" +
	"request_id\x18\x06 \x01(\tR\trequestId\";\n" +
	"\rEndpointUsage\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"C\n" +
	"\x1dRegisterConsumerUsageResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged2\x81\x02\n" +
	"\x10RegistryProvider\x12f\n" +
	"\vFetchSchema\x12*.cvt.plugin.registry.v1.FetchSchemaRequest\x1a+.cvt.plugin.registry.v1.FetchSchemaResponse\x12\x84\x01\n" +
	"\x15RegisterConsumerUsage\x124.cvt.plugin.registry.v1.RegisterConsumerUsageRequest\x1a5.cvt.plugin.registry.v1.RegisterConsumerUsageResponseB?Z=github.com/sahina/cvt/pkg/cvtplugin/pb/registry/v1;registrypbb\x06proto3"

var (
	file_api_protos_plugin_registry_v1_registry_proto_rawDescOnce sync.Once
	file_api_protos_plugin_registry_v1_registry_proto_rawDescData []byte
)

func file_api_protos_plugin_registry_v1_registry_proto_rawDescGZIP() []byte {
	file_api_protos_plugin_registry_v1_registry_proto_rawDescOnce.Do(func() {
		file_api_protos_plugin_registry_v1_registry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_protos_plugin_registry_v1_registry_proto_rawDesc), len(file_api_protos_plugin_registry_v1_registry_proto_rawDesc)))
	})
	return file_api_protos_plugin_registry_v1_registry_proto_rawDescData
}

var file_api_protos_plugin_registry_v1_registry_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_protos_plugin_registry_v1_registry_proto_goTypes = []any{
	(*FetchSchemaRequest)(nil),            // 0: cvt.plugin.registry.v1.FetchSchemaRequest
	(*FetchSchemaResponse)(nil),           // 1: cvt.plugin.registry.v1.FetchSchemaResponse
	(*RegisterConsumerUsageRequest)(nil),  // 2: cvt.plugin.registry.v1.RegisterConsumerUsageRequest
	(*EndpointUsage)(nil),                 // 3: cvt.plugin.registry.v1.EndpointUsage
	(*RegisterConsumerUsageResponse)(nil), // 4: cvt.plugin.registry.v1.RegisterConsumerUsageResponse
}
var file_api_protos_plugin_registry_v1_registry_proto_depIdxs = []int32{
	3, // 0: cvt.plugin.registry.v1.RegisterConsumerUsageRequest.endpoints:type_name -> cvt.plugin.registry.v1.EndpointUsage
	0, // 1: cvt.plugin.registry.v1.RegistryProvider.FetchSchema:input_type -> cvt.plugin.registry.v1.FetchSchemaRequest
	2, // 2: cvt.plugin.registry.v1.RegistryProvider.RegisterConsumerUsage:input_type -> cvt.plugin.registry.v1.RegisterConsumerUsageRequest
	1, // 3: cvt.plugin.registry.v1.RegistryProvider.FetchSchema:output_type -> cvt.plugin.registry.v1.FetchSchemaResponse
	4, // 4: cvt.plugin.registry.v1.RegistryProvider.RegisterConsumerUsage:output_type -> cvt.plugin.registry.v1.RegisterConsumerUsageResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_protos_plugin_registry_v1_registry_proto_init() }
func file_api_protos_plugin_registry_v1_registry_proto_init() {
	if File_api_protos_plugin_registry_v1_registry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_protos_plugin_registry_v1_registry_proto_rawDesc), len(file_api_protos_plugin_registry_v1_registry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_protos_plugin_registry_v1_registry_proto_goTypes,
		DependencyIndexes: file_api_protos_plugin_registry_v1_registry_proto_depIdxs,
		MessageInfos:      file_api_protos_plugin_registry_v1_registry_proto_msgTypes,
	}.Build()
	File_api_protos_plugin_registry_v1_registry_proto = out.File
	file_api_protos_plugin_registry_v1_registry_proto_goTypes = nil
	file_api_protos_plugin_registry_v1_registry_proto_depIdxs = nil
}
