// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/protos/plugin/handshake.proto

package handshakepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthResponse_Status int32

const (
	HealthResponse_UNKNOWN     HealthResponse_Status = 0
	HealthResponse_SERVING     HealthResponse_Status = 1
	HealthResponse_NOT_SERVING HealthResponse_Status = 2
)

// Enum value maps for HealthResponse_Status.
var (
	HealthResponse_Status_name = map[int32]string{
		0: "UNKNOWN",
		1: "SERVING",
		2: "NOT_SERVING",
	}
	HealthResponse_Status_value = map[string]int32{
		"UNKNOWN":     0,
		"SERVING":     1,
		"NOT_SERVING": 2,
	}
)

func (x HealthResponse_Status) Enum() *HealthResponse_Status {
	p := new(HealthResponse_Status)
	*p = x
	return p
}

func (x HealthResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_api_protos_plugin_handshake_proto_enumTypes[0].Descriptor()
}

func (HealthResponse_Status) Type() protoreflect.EnumType {
	return &file_api_protos_plugin_handshake_proto_enumTypes[0]
}

func (x HealthResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthResponse_Status.Descriptor instead.
func (HealthResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_api_protos_plugin_handshake_proto_rawDescGZIP(), []int{3, 0}
}

type InfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoRequest) Reset() {
	*x = InfoRequest{}
	mi := &file_api_protos_plugin_handshake_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoRequest) ProtoMessage() {}

func (x *InfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_plugin_handshake_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoRequest.ProtoReflect.Descriptor instead.
func (*InfoRequest) Descriptor() ([]byte, []int) {
	return file_api_protos_plugin_handshake_proto_rawDescGZIP(), []int{0}
}

type InfoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Plugin's self-reported name. Not trusted; recorded as reported_name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Plugin's self-reported version. Not trusted; recorded as reported_version.
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// Services the plugin implements, e.g., ["registry.v1", "events.v1"].
	Services []string `protobuf:"bytes,3,rep,name=services,proto3" json:"services,omitempty"`
	// CVT plugin protocol version. Mismatch with core = plugin rejected.
	ProtocolVersion uint32 `protobuf:"varint,4,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InfoResponse) Reset() {
	*x = InfoResponse{}
	mi := &file_api_protos_plugin_handshake_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoResponse) ProtoMessage() {}

func (x *InfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_plugin_handshake_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoResponse.ProtoReflect.Descriptor instead.
func (*InfoResponse) Descriptor() ([]byte, []int) {
	return file_api_protos_plugin_handshake_proto_rawDescGZIP(), []int{1}
}

func (x *InfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InfoResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *InfoResponse) GetServices() []string {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *InfoResponse) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_api_protos_plugin_handshake_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_plugin_handshake_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_api_protos_plugin_handshake_proto_rawDescGZIP(), []int{2}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        HealthResponse_Status  `protobuf:"varint,1,opt,name=status,proto3,enum=cvt.plugin.handshake.v1.HealthResponse_Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_api_protos_plugin_handshake_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_plugin_handshake_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_api_protos_plugin_handshake_proto_rawDescGZIP(), []int{3}
}

func (x *HealthResponse) GetStatus() HealthResponse_Status {
	if x != nil {
		return x.Status
	}
	return HealthResponse_UNKNOWN
}

type SetConfigRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Config key. For non-secret keys, this corresponds to an entry under
	// `plugins.<name>.config:` in the CVT config file. For secret keys, this
	// corresponds to a name listed in `plugins.<name>.secrets:`.
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Config value, after environment variable interpolation has been applied
	// by core. Secret values are never logged by core and must not be logged
	// by the plugin.
	Value         string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetConfigRequest) Reset() {
	*x = SetConfigRequest{}
	mi := &file_api_protos_plugin_handshake_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetConfigRequest) ProtoMessage() {}

func (x *SetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_plugin_handshake_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetConfigRequest.ProtoReflect.Descriptor instead.
func (*SetConfigRequest) Descriptor() ([]byte, []int) {
	return file_api_protos_plugin_handshake_proto_rawDescGZIP(), []int{4}
}

func (x *SetConfigRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetConfigRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type SetConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetConfigResponse) Reset() {
	*x = SetConfigResponse{}
	mi := &file_api_protos_plugin_handshake_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetConfigResponse) ProtoMessage() {}

func (x *SetConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_plugin_handshake_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetConfigResponse.ProtoReflect.Descriptor instead.
func (*SetConfigResponse) Descriptor() ([]byte, []int) {
	return file_api_protos_plugin_handshake_proto_rawDescGZIP(), []int{5}
}

var File_api_protos_plugin_handshake_proto protoreflect.FileDescriptor

const file_api_protos_plugin_handshake_proto_rawDesc = "" +
	"\n" +
	"!api/protos/plugin/handshake.proto\x12\x17cvt.plugin.handshake.v1\"\r\n" +
	"\vInfoRequest\"\x83\x01\n" +
	"\fInfoResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1a\n" +
	"\bservices\x18\x03 \x03(\tR\bservices\x12)\n" +
	"\x10protocol_version\x18\x04 \x01(\rR\x0fprotocolVersion\"\x0f\n" +
	"\rHealthRequest\"\x8d\x01\n" +
	"\x0eHealthResponse\x12F\n" +
	"\x06status\x18\x01 \x01(\x0e2..cvt.plugin.handshake.v1.HealthResponse.StatusR\x06status\"3\n" +
	"\x06Status\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aSERVING\x10\x01\x12\x0f\n" +
	"\vNOT_SERVING\x10\x02\":\n" +
	"\x10SetConfigRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\x13\n" +
	"\x11SetConfigResponse2\xa5\x02\n" +
	"\x0fPluginHandshake\x12S\n" +
	"\x04Info\x12$.cvt.plugin.handshake.v1.InfoRequest\x1a%.cvt.plugin.handshake.v1.InfoResponse\x12Y\n" +
	"\x06Health\x12&.cvt.plugin.handshake.v1.HealthRequest\x1a'.cvt.plugin.handshake.v1.HealthResponse\x12b\n" +
	"\tSetConfig\x12).cvt.plugin.handshake.v1.SetConfigRequest\x1a*.cvt.plugin.handshake.v1.SetConfigResponseBAZ?github.com/sahina/cvt/pkg/cvtplugin/pb/handshake/v1;handshakepbb\x06proto3"

var (
	file_api_protos_plugin_handshake_proto_rawDescOnce sync.Once
	file_api_protos_plugin_handshake_proto_rawDescData []byte
)

func file_api_protos_plugin_handshake_proto_rawDescGZIP() []byte {
	file_api_protos_plugin_handshake_proto_rawDescOnce.Do(func() {
		file_api_protos_plugin_handshake_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_protos_plugin_handshake_proto_rawDesc), len(file_api_protos_plugin_handshake_proto_rawDesc)))
	})
	return file_api_protos_plugin_handshake_proto_rawDescData
}

var file_api_protos_plugin_handshake_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_protos_plugin_handshake_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_protos_plugin_handshake_proto_goTypes = []any{
	(HealthResponse_Status)(0), // 0: cvt.plugin.handshake.v1.HealthResponse.Status
	(*InfoRequest)(nil),        // 1: cvt.plugin.handshake.v1.InfoRequest
	(*InfoResponse)(nil),       // 2: cvt.plugin.handshake.v1.InfoResponse
	(*HealthRequest)(nil),      // 3: cvt.plugin.handshake.v1.HealthRequest
	(*HealthResponse)(nil),     // 4: cvt.plugin.handshake.v1.HealthResponse
	(*SetConfigRequest)(nil),   // 5: cvt.plugin.handshake.v1.SetConfigRequest
	(*SetConfigResponse)(nil),  // 6: cvt.plugin.handshake.v1.SetConfigResponse
}
var file_api_protos_plugin_handshake_proto_depIdxs = []int32{
	0, // 0: cvt.plugin.handshake.v1.HealthResponse.status:type_name -> cvt.plugin.handshake.v1.HealthResponse.Status
	1, // 1: cvt.plugin.handshake.v1.PluginHandshake.Info:input_type -> cvt.plugin.handshake.v1.InfoRequest
	3, // 2: cvt.plugin.handshake.v1.PluginHandshake.Health:input_type -> cvt.plugin.handshake.v1.HealthRequest
	5, // 3: cvt.plugin.handshake.v1.PluginHandshake.SetConfig:input_type -> cvt.plugin.handshake.v1.SetConfigRequest
	2, // 4: cvt.plugin.handshake.v1.PluginHandshake.Info:output_type -> cvt.plugin.handshake.v1.InfoResponse
	4, // 5: cvt.plugin.handshake.v1.PluginHandshake.Health:output_type -> cvt.plugin.handshake.v1.HealthResponse
	6, // 6: cvt.plugin.handshake.v1.PluginHandshake.SetConfig:output_type -> cvt.plugin.handshake.v1.SetConfigResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_protos_plugin_handshake_proto_init() }
func file_api_protos_plugin_handshake_proto_init() {
	if File_api_protos_plugin_handshake_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_protos_plugin_handshake_proto_rawDesc), len(file_api_protos_plugin_handshake_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_protos_plugin_handshake_proto_goTypes,
		DependencyIndexes: file_api_protos_plugin_handshake_proto_depIdxs,
		EnumInfos:         file_api_protos_plugin_handshake_proto_enumTypes,
		MessageInfos:      file_api_protos_plugin_handshake_proto_msgTypes,
	}.Build()
	File_api_protos_plugin_handshake_proto = out.File
	file_api_protos_plugin_handshake_proto_goTypes = nil
	file_api_protos_plugin_handshake_proto_depIdxs = nil
}
