// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v7.34.1
// source: api/protos/plugin/handshake.proto

package handshakepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PluginHandshakeClient is the client API for PluginHandshake service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PluginHandshakeClient interface {
	// Info returns plugin identity and the list of CVT plugin services the
	// plugin implements. Called by core exactly once, right after go-plugin
	// establishes the gRPC transport, within a 5s total deadline.
	Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error)
	// Health is polled periodically by core. SERVING = ready; anything else
	// triggers supervisor restart per config.
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	// SetConfig delivers config values to the plugin, including secret keys
	// declared in `plugins.<name>.secrets`. Core calls SetConfig once per
	// key after Info succeeds and before any extension-point RPC is invoked.
	// Secrets travel over the gRPC transport, not the subprocess environment.
	SetConfig(ctx context.Context, in *SetConfigRequest, opts ...grpc.CallOption) (*SetConfigResponse, error)
}

type pluginHandshakeClient struct {
	cc grpc.ClientConnInterface
}

func NewPluginHandshakeClient(cc grpc.ClientConnInterface) PluginHandshakeClient {
	return &pluginHandshakeClient{cc}
}

func (c *pluginHandshakeClient) Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error) {
	out := new(InfoResponse)
	err := c.cc.Invoke(ctx, "/cvt.plugin.handshake.v1.PluginHandshake/Info", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginHandshakeClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, "/cvt.plugin.handshake.v1.PluginHandshake/Health", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginHandshakeClient) SetConfig(ctx context.Context, in *SetConfigRequest, opts ...grpc.CallOption) (*SetConfigResponse, error) {
	out := new(SetConfigResponse)
	err := c.cc.Invoke(ctx, "/cvt.plugin.handshake.v1.PluginHandshake/SetConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PluginHandshakeServer is the server API for PluginHandshake service.
// All implementations must embed UnimplementedPluginHandshakeServer
// for forward compatibility
type PluginHandshakeServer interface {
	// Info returns plugin identity and the list of CVT plugin services the
	// plugin implements. Called by core exactly once, right after go-plugin
	// establishes the gRPC transport, within a 5s total deadline.
	Info(context.Context, *InfoRequest) (*InfoResponse, error)
	// Health is polled periodically by core. SERVING = ready; anything else
	// triggers supervisor restart per config.
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	// SetConfig delivers config values to the plugin, including secret keys
	// declared in `plugins.<name>.secrets`. Core calls SetConfig once per
	// key after Info succeeds and before any extension-point RPC is invoked.
	// Secrets travel over the gRPC transport, not the subprocess environment.
	SetConfig(context.Context, *SetConfigRequest) (*SetConfigResponse, error)
	mustEmbedUnimplementedPluginHandshakeServer()
}

// UnimplementedPluginHandshakeServer must be embedded to have forward compatible implementations.
type UnimplementedPluginHandshakeServer struct {
}

func (UnimplementedPluginHandshakeServer) Info(context.Context, *InfoRequest) (*InfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Info not implemented")
}
func (UnimplementedPluginHandshakeServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedPluginHandshakeServer) SetConfig(context.Context, *SetConfigRequest) (*SetConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetConfig not implemented")
}
func (UnimplementedPluginHandshakeServer) mustEmbedUnimplementedPluginHandshakeServer() {}

// UnsafePluginHandshakeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PluginHandshakeServer will
// result in compilation errors.
type UnsafePluginHandshakeServer interface {
	mustEmbedUnimplementedPluginHandshakeServer()
}

func RegisterPluginHandshakeServer(s grpc.ServiceRegistrar, srv PluginHandshakeServer) {
	s.RegisterService(&PluginHandshake_ServiceDesc, srv)
}

func _PluginHandshake_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginHandshakeServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cvt.plugin.handshake.v1.PluginHandshake/Info",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginHandshakeServer).Info(ctx, req.(*InfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginHandshake_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginHandshakeServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cvt.plugin.handshake.v1.PluginHandshake/Health",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginHandshakeServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginHandshake_SetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginHandshakeServer).SetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cvt.plugin.handshake.v1.PluginHandshake/SetConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginHandshakeServer).SetConfig(ctx, req.(*SetConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PluginHandshake_ServiceDesc is the grpc.ServiceDesc for PluginHandshake service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PluginHandshake_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cvt.plugin.handshake.v1.PluginHandshake",
	HandlerType: (*PluginHandshakeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Info",
			Handler:    _PluginHandshake_Info_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _PluginHandshake_Health_Handler,
		},
		{
			MethodName: "SetConfig",
			Handler:    _PluginHandshake_SetConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/protos/plugin/handshake.proto",
}
